-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2014.4
-- Copyright (C) 2014 Xilinx Inc. All rights reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel is
port (
    INPUT_STREAM_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    INPUT_STREAM_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    rows : IN STD_LOGIC_VECTOR (31 downto 0);
    cols : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    INPUT_STREAM_TVALID : IN STD_LOGIC;
    INPUT_STREAM_TREADY : OUT STD_LOGIC;
    OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
    OUTPUT_STREAM_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC );
end;


architecture behav of sobel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sobel,hls_ip_2014_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-1,HLS_INPUT_CLOCK=8.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.861850,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=1727,HLS_SYN_LUT=3423}";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_true : BOOLEAN := true;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_logic_1 : STD_LOGIC := '1';

    signal ap_rst_n_inv : STD_LOGIC;
    signal sobel_Block_proc_U0_ap_start : STD_LOGIC;
    signal sobel_Block_proc_U0_ap_done : STD_LOGIC;
    signal sobel_Block_proc_U0_ap_continue : STD_LOGIC;
    signal sobel_Block_proc_U0_ap_idle : STD_LOGIC;
    signal sobel_Block_proc_U0_ap_ready : STD_LOGIC;
    signal sobel_Block_proc_U0_rows : STD_LOGIC_VECTOR (31 downto 0);
    signal sobel_Block_proc_U0_cols : STD_LOGIC_VECTOR (31 downto 0);
    signal sobel_Block_proc_U0_ap_return_0 : STD_LOGIC_VECTOR (11 downto 0);
    signal sobel_Block_proc_U0_ap_return_1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sobel_Block_proc_U0_ap_return_2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sobel_Block_proc_U0_ap_return_3 : STD_LOGIC_VECTOR (11 downto 0);
    signal sobel_Block_proc_U0_ap_return_4 : STD_LOGIC_VECTOR (11 downto 0);
    signal sobel_Block_proc_U0_ap_return_5 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel : STD_LOGIC;
    signal img_0_rows_V_channel_full_n : STD_LOGIC;
    signal ap_reg_ready_img_0_rows_V_channel_full_n : STD_LOGIC := '0';
    signal ap_sig_ready_img_0_rows_V_channel_full_n : STD_LOGIC;
    signal ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel : STD_LOGIC;
    signal img_0_cols_V_channel_full_n : STD_LOGIC;
    signal ap_reg_ready_img_0_cols_V_channel_full_n : STD_LOGIC := '0';
    signal ap_sig_ready_img_0_cols_V_channel_full_n : STD_LOGIC;
    signal ap_chn_write_sobel_Block_proc_U0_img_1_cols_V : STD_LOGIC;
    signal img_1_cols_V_full_n : STD_LOGIC;
    signal ap_reg_ready_img_1_cols_V_full_n : STD_LOGIC := '0';
    signal ap_sig_ready_img_1_cols_V_full_n : STD_LOGIC;
    signal ap_chn_write_sobel_Block_proc_U0_img_1_rows_V : STD_LOGIC;
    signal img_1_rows_V_full_n : STD_LOGIC;
    signal ap_reg_ready_img_1_rows_V_full_n : STD_LOGIC := '0';
    signal ap_sig_ready_img_1_rows_V_full_n : STD_LOGIC;
    signal ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel1 : STD_LOGIC;
    signal img_0_rows_V_channel1_full_n : STD_LOGIC;
    signal ap_reg_ready_img_0_rows_V_channel1_full_n : STD_LOGIC := '0';
    signal ap_sig_ready_img_0_rows_V_channel1_full_n : STD_LOGIC;
    signal ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel1 : STD_LOGIC;
    signal img_0_cols_V_channel1_full_n : STD_LOGIC;
    signal ap_reg_ready_img_0_cols_V_channel1_full_n : STD_LOGIC := '0';
    signal ap_sig_ready_img_0_cols_V_channel1_full_n : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_ap_start : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_ap_done : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_ap_continue : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_ap_idle : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_ap_ready : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal sobel_AXIvideo2Mat_U0_INPUT_STREAM_TVALID : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_INPUT_STREAM_TREADY : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal sobel_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal sobel_AXIvideo2Mat_U0_INPUT_STREAM_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal sobel_AXIvideo2Mat_U0_INPUT_STREAM_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal sobel_AXIvideo2Mat_U0_INPUT_STREAM_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal sobel_AXIvideo2Mat_U0_img_rows_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal sobel_AXIvideo2Mat_U0_img_cols_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal sobel_AXIvideo2Mat_U0_img_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_AXIvideo2Mat_U0_img_data_stream_0_V_full_n : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_img_data_stream_0_V_write : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_img_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_AXIvideo2Mat_U0_img_data_stream_1_V_full_n : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_img_data_stream_1_V_write : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_img_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_AXIvideo2Mat_U0_img_data_stream_2_V_full_n : STD_LOGIC;
    signal sobel_AXIvideo2Mat_U0_img_data_stream_2_V_write : STD_LOGIC;
    signal sobel_Sobel_U0_ap_start : STD_LOGIC;
    signal sobel_Sobel_U0_ap_done : STD_LOGIC;
    signal sobel_Sobel_U0_ap_continue : STD_LOGIC;
    signal sobel_Sobel_U0_ap_idle : STD_LOGIC;
    signal sobel_Sobel_U0_ap_ready : STD_LOGIC;
    signal sobel_Sobel_U0_p_src_rows_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal sobel_Sobel_U0_p_src_cols_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal sobel_Sobel_U0_p_src_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_Sobel_U0_p_src_data_stream_0_V_empty_n : STD_LOGIC;
    signal sobel_Sobel_U0_p_src_data_stream_0_V_read : STD_LOGIC;
    signal sobel_Sobel_U0_p_src_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_Sobel_U0_p_src_data_stream_1_V_empty_n : STD_LOGIC;
    signal sobel_Sobel_U0_p_src_data_stream_1_V_read : STD_LOGIC;
    signal sobel_Sobel_U0_p_src_data_stream_2_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_Sobel_U0_p_src_data_stream_2_V_empty_n : STD_LOGIC;
    signal sobel_Sobel_U0_p_src_data_stream_2_V_read : STD_LOGIC;
    signal sobel_Sobel_U0_p_dst_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_Sobel_U0_p_dst_data_stream_0_V_full_n : STD_LOGIC;
    signal sobel_Sobel_U0_p_dst_data_stream_0_V_write : STD_LOGIC;
    signal sobel_Sobel_U0_p_dst_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_Sobel_U0_p_dst_data_stream_1_V_full_n : STD_LOGIC;
    signal sobel_Sobel_U0_p_dst_data_stream_1_V_write : STD_LOGIC;
    signal sobel_Sobel_U0_p_dst_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_Sobel_U0_p_dst_data_stream_2_V_full_n : STD_LOGIC;
    signal sobel_Sobel_U0_p_dst_data_stream_2_V_write : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_ap_start : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_ap_done : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_ap_continue : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_ap_idle : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_ap_ready : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_img_rows_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal sobel_Mat2AXIvideo_U0_img_cols_V_read : STD_LOGIC_VECTOR (11 downto 0);
    signal sobel_Mat2AXIvideo_U0_img_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_img_data_stream_0_V_read : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_img_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_img_data_stream_1_V_read : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_img_data_stream_2_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal sobel_Mat2AXIvideo_U0_img_data_stream_2_V_empty_n : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_img_data_stream_2_V_read : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TREADY : STD_LOGIC;
    signal sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sig_hs_continue : STD_LOGIC;
    signal img_0_rows_V_channel_U_ap_dummy_ce : STD_LOGIC;
    signal img_0_rows_V_channel_din : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_rows_V_channel_write : STD_LOGIC;
    signal img_0_rows_V_channel_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_rows_V_channel_empty_n : STD_LOGIC;
    signal img_0_rows_V_channel_read : STD_LOGIC;
    signal img_0_rows_V_channel1_U_ap_dummy_ce : STD_LOGIC;
    signal img_0_rows_V_channel1_din : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_rows_V_channel1_write : STD_LOGIC;
    signal img_0_rows_V_channel1_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_rows_V_channel1_empty_n : STD_LOGIC;
    signal img_0_rows_V_channel1_read : STD_LOGIC;
    signal img_0_cols_V_channel_U_ap_dummy_ce : STD_LOGIC;
    signal img_0_cols_V_channel_din : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_cols_V_channel_write : STD_LOGIC;
    signal img_0_cols_V_channel_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_cols_V_channel_empty_n : STD_LOGIC;
    signal img_0_cols_V_channel_read : STD_LOGIC;
    signal img_0_cols_V_channel1_U_ap_dummy_ce : STD_LOGIC;
    signal img_0_cols_V_channel1_din : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_cols_V_channel1_write : STD_LOGIC;
    signal img_0_cols_V_channel1_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal img_0_cols_V_channel1_empty_n : STD_LOGIC;
    signal img_0_cols_V_channel1_read : STD_LOGIC;
    signal img_1_rows_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_1_rows_V_din : STD_LOGIC_VECTOR (11 downto 0);
    signal img_1_rows_V_write : STD_LOGIC;
    signal img_1_rows_V_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal img_1_rows_V_empty_n : STD_LOGIC;
    signal img_1_rows_V_read : STD_LOGIC;
    signal img_1_cols_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_1_cols_V_din : STD_LOGIC_VECTOR (11 downto 0);
    signal img_1_cols_V_write : STD_LOGIC;
    signal img_1_cols_V_dout : STD_LOGIC_VECTOR (11 downto 0);
    signal img_1_cols_V_empty_n : STD_LOGIC;
    signal img_1_cols_V_read : STD_LOGIC;
    signal img_0_data_stream_0_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_0_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_0_V_full_n : STD_LOGIC;
    signal img_0_data_stream_0_V_write : STD_LOGIC;
    signal img_0_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_0_V_empty_n : STD_LOGIC;
    signal img_0_data_stream_0_V_read : STD_LOGIC;
    signal img_0_data_stream_1_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_0_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_1_V_full_n : STD_LOGIC;
    signal img_0_data_stream_1_V_write : STD_LOGIC;
    signal img_0_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_1_V_empty_n : STD_LOGIC;
    signal img_0_data_stream_1_V_read : STD_LOGIC;
    signal img_0_data_stream_2_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_0_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_2_V_full_n : STD_LOGIC;
    signal img_0_data_stream_2_V_write : STD_LOGIC;
    signal img_0_data_stream_2_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_2_V_empty_n : STD_LOGIC;
    signal img_0_data_stream_2_V_read : STD_LOGIC;
    signal img_1_data_stream_0_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_1_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_0_V_full_n : STD_LOGIC;
    signal img_1_data_stream_0_V_write : STD_LOGIC;
    signal img_1_data_stream_0_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_0_V_empty_n : STD_LOGIC;
    signal img_1_data_stream_0_V_read : STD_LOGIC;
    signal img_1_data_stream_1_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_1_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_1_V_full_n : STD_LOGIC;
    signal img_1_data_stream_1_V_write : STD_LOGIC;
    signal img_1_data_stream_1_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_1_V_empty_n : STD_LOGIC;
    signal img_1_data_stream_1_V_read : STD_LOGIC;
    signal img_1_data_stream_2_V_U_ap_dummy_ce : STD_LOGIC;
    signal img_1_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_2_V_full_n : STD_LOGIC;
    signal img_1_data_stream_2_V_write : STD_LOGIC;
    signal img_1_data_stream_2_V_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_2_V_empty_n : STD_LOGIC;
    signal img_1_data_stream_2_V_read : STD_LOGIC;
    signal ap_reg_procdone_sobel_Block_proc_U0 : STD_LOGIC := '0';
    signal ap_sig_hs_done : STD_LOGIC;
    signal ap_reg_procdone_sobel_AXIvideo2Mat_U0 : STD_LOGIC := '0';
    signal ap_reg_procdone_sobel_Sobel_U0 : STD_LOGIC := '0';
    signal ap_reg_procdone_sobel_Mat2AXIvideo_U0 : STD_LOGIC := '0';
    signal ap_CS : STD_LOGIC;
    signal ap_sig_top_allready : STD_LOGIC;

    component sobel_Block_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        rows : IN STD_LOGIC_VECTOR (31 downto 0);
        cols : IN STD_LOGIC_VECTOR (31 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (11 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (11 downto 0) );
    end component;


    component sobel_AXIvideo2Mat IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        INPUT_STREAM_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        INPUT_STREAM_TVALID : IN STD_LOGIC;
        INPUT_STREAM_TREADY : OUT STD_LOGIC;
        INPUT_STREAM_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        INPUT_STREAM_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        INPUT_STREAM_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        INPUT_STREAM_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        INPUT_STREAM_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        INPUT_STREAM_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        img_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        img_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        img_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_full_n : IN STD_LOGIC;
        img_data_stream_0_V_write : OUT STD_LOGIC;
        img_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_full_n : IN STD_LOGIC;
        img_data_stream_1_V_write : OUT STD_LOGIC;
        img_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_2_V_full_n : IN STD_LOGIC;
        img_data_stream_2_V_write : OUT STD_LOGIC );
    end component;


    component sobel_Sobel IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_src_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        p_src_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        p_src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_0_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_0_V_read : OUT STD_LOGIC;
        p_src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_1_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_1_V_read : OUT STD_LOGIC;
        p_src_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_2_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_2_V_read : OUT STD_LOGIC;
        p_dst_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_0_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_0_V_write : OUT STD_LOGIC;
        p_dst_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_1_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_1_V_write : OUT STD_LOGIC;
        p_dst_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_2_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_2_V_write : OUT STD_LOGIC );
    end component;


    component sobel_Mat2AXIvideo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_rows_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        img_cols_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        img_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_data_stream_0_V_read : OUT STD_LOGIC;
        img_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_data_stream_1_V_read : OUT STD_LOGIC;
        img_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_2_V_empty_n : IN STD_LOGIC;
        img_data_stream_2_V_read : OUT STD_LOGIC;
        OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
        OUTPUT_STREAM_TREADY : IN STD_LOGIC;
        OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        OUTPUT_STREAM_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        OUTPUT_STREAM_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        OUTPUT_STREAM_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component FIFO_sobel_img_0_rows_V_channel IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_sobel_img_0_rows_V_channel1 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_sobel_img_0_cols_V_channel IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_sobel_img_0_cols_V_channel1 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_sobel_img_1_rows_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_sobel_img_1_cols_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (11 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (11 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_sobel_img_0_data_stream_0_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_sobel_img_0_data_stream_1_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_sobel_img_0_data_stream_2_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_sobel_img_1_data_stream_0_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_sobel_img_1_data_stream_1_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component FIFO_sobel_img_1_data_stream_2_V IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    sobel_Block_proc_U0 : component sobel_Block_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => sobel_Block_proc_U0_ap_start,
        ap_done => sobel_Block_proc_U0_ap_done,
        ap_continue => sobel_Block_proc_U0_ap_continue,
        ap_idle => sobel_Block_proc_U0_ap_idle,
        ap_ready => sobel_Block_proc_U0_ap_ready,
        rows => sobel_Block_proc_U0_rows,
        cols => sobel_Block_proc_U0_cols,
        ap_return_0 => sobel_Block_proc_U0_ap_return_0,
        ap_return_1 => sobel_Block_proc_U0_ap_return_1,
        ap_return_2 => sobel_Block_proc_U0_ap_return_2,
        ap_return_3 => sobel_Block_proc_U0_ap_return_3,
        ap_return_4 => sobel_Block_proc_U0_ap_return_4,
        ap_return_5 => sobel_Block_proc_U0_ap_return_5);

    sobel_AXIvideo2Mat_U0 : component sobel_AXIvideo2Mat
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => sobel_AXIvideo2Mat_U0_ap_start,
        ap_done => sobel_AXIvideo2Mat_U0_ap_done,
        ap_continue => sobel_AXIvideo2Mat_U0_ap_continue,
        ap_idle => sobel_AXIvideo2Mat_U0_ap_idle,
        ap_ready => sobel_AXIvideo2Mat_U0_ap_ready,
        INPUT_STREAM_TDATA => sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDATA,
        INPUT_STREAM_TVALID => sobel_AXIvideo2Mat_U0_INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY => sobel_AXIvideo2Mat_U0_INPUT_STREAM_TREADY,
        INPUT_STREAM_TKEEP => sobel_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB => sobel_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER => sobel_AXIvideo2Mat_U0_INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST => sobel_AXIvideo2Mat_U0_INPUT_STREAM_TLAST,
        INPUT_STREAM_TID => sobel_AXIvideo2Mat_U0_INPUT_STREAM_TID,
        INPUT_STREAM_TDEST => sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDEST,
        img_rows_V_read => sobel_AXIvideo2Mat_U0_img_rows_V_read,
        img_cols_V_read => sobel_AXIvideo2Mat_U0_img_cols_V_read,
        img_data_stream_0_V_din => sobel_AXIvideo2Mat_U0_img_data_stream_0_V_din,
        img_data_stream_0_V_full_n => sobel_AXIvideo2Mat_U0_img_data_stream_0_V_full_n,
        img_data_stream_0_V_write => sobel_AXIvideo2Mat_U0_img_data_stream_0_V_write,
        img_data_stream_1_V_din => sobel_AXIvideo2Mat_U0_img_data_stream_1_V_din,
        img_data_stream_1_V_full_n => sobel_AXIvideo2Mat_U0_img_data_stream_1_V_full_n,
        img_data_stream_1_V_write => sobel_AXIvideo2Mat_U0_img_data_stream_1_V_write,
        img_data_stream_2_V_din => sobel_AXIvideo2Mat_U0_img_data_stream_2_V_din,
        img_data_stream_2_V_full_n => sobel_AXIvideo2Mat_U0_img_data_stream_2_V_full_n,
        img_data_stream_2_V_write => sobel_AXIvideo2Mat_U0_img_data_stream_2_V_write);

    sobel_Sobel_U0 : component sobel_Sobel
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => sobel_Sobel_U0_ap_start,
        ap_done => sobel_Sobel_U0_ap_done,
        ap_continue => sobel_Sobel_U0_ap_continue,
        ap_idle => sobel_Sobel_U0_ap_idle,
        ap_ready => sobel_Sobel_U0_ap_ready,
        p_src_rows_V_read => sobel_Sobel_U0_p_src_rows_V_read,
        p_src_cols_V_read => sobel_Sobel_U0_p_src_cols_V_read,
        p_src_data_stream_0_V_dout => sobel_Sobel_U0_p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n => sobel_Sobel_U0_p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read => sobel_Sobel_U0_p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout => sobel_Sobel_U0_p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n => sobel_Sobel_U0_p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read => sobel_Sobel_U0_p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout => sobel_Sobel_U0_p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n => sobel_Sobel_U0_p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read => sobel_Sobel_U0_p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din => sobel_Sobel_U0_p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n => sobel_Sobel_U0_p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write => sobel_Sobel_U0_p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din => sobel_Sobel_U0_p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n => sobel_Sobel_U0_p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write => sobel_Sobel_U0_p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din => sobel_Sobel_U0_p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n => sobel_Sobel_U0_p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write => sobel_Sobel_U0_p_dst_data_stream_2_V_write);

    sobel_Mat2AXIvideo_U0 : component sobel_Mat2AXIvideo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => sobel_Mat2AXIvideo_U0_ap_start,
        ap_done => sobel_Mat2AXIvideo_U0_ap_done,
        ap_continue => sobel_Mat2AXIvideo_U0_ap_continue,
        ap_idle => sobel_Mat2AXIvideo_U0_ap_idle,
        ap_ready => sobel_Mat2AXIvideo_U0_ap_ready,
        img_rows_V_read => sobel_Mat2AXIvideo_U0_img_rows_V_read,
        img_cols_V_read => sobel_Mat2AXIvideo_U0_img_cols_V_read,
        img_data_stream_0_V_dout => sobel_Mat2AXIvideo_U0_img_data_stream_0_V_dout,
        img_data_stream_0_V_empty_n => sobel_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n,
        img_data_stream_0_V_read => sobel_Mat2AXIvideo_U0_img_data_stream_0_V_read,
        img_data_stream_1_V_dout => sobel_Mat2AXIvideo_U0_img_data_stream_1_V_dout,
        img_data_stream_1_V_empty_n => sobel_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n,
        img_data_stream_1_V_read => sobel_Mat2AXIvideo_U0_img_data_stream_1_V_read,
        img_data_stream_2_V_dout => sobel_Mat2AXIvideo_U0_img_data_stream_2_V_dout,
        img_data_stream_2_V_empty_n => sobel_Mat2AXIvideo_U0_img_data_stream_2_V_empty_n,
        img_data_stream_2_V_read => sobel_Mat2AXIvideo_U0_img_data_stream_2_V_read,
        OUTPUT_STREAM_TDATA => sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID => sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY => sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TREADY,
        OUTPUT_STREAM_TKEEP => sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB => sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER => sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST => sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID => sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST => sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST);

    img_0_rows_V_channel_U : component FIFO_sobel_img_0_rows_V_channel
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_0_rows_V_channel_U_ap_dummy_ce,
        if_write_ce => img_0_rows_V_channel_U_ap_dummy_ce,
        if_din => img_0_rows_V_channel_din,
        if_full_n => img_0_rows_V_channel_full_n,
        if_write => img_0_rows_V_channel_write,
        if_dout => img_0_rows_V_channel_dout,
        if_empty_n => img_0_rows_V_channel_empty_n,
        if_read => img_0_rows_V_channel_read);

    img_0_rows_V_channel1_U : component FIFO_sobel_img_0_rows_V_channel1
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_0_rows_V_channel1_U_ap_dummy_ce,
        if_write_ce => img_0_rows_V_channel1_U_ap_dummy_ce,
        if_din => img_0_rows_V_channel1_din,
        if_full_n => img_0_rows_V_channel1_full_n,
        if_write => img_0_rows_V_channel1_write,
        if_dout => img_0_rows_V_channel1_dout,
        if_empty_n => img_0_rows_V_channel1_empty_n,
        if_read => img_0_rows_V_channel1_read);

    img_0_cols_V_channel_U : component FIFO_sobel_img_0_cols_V_channel
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_0_cols_V_channel_U_ap_dummy_ce,
        if_write_ce => img_0_cols_V_channel_U_ap_dummy_ce,
        if_din => img_0_cols_V_channel_din,
        if_full_n => img_0_cols_V_channel_full_n,
        if_write => img_0_cols_V_channel_write,
        if_dout => img_0_cols_V_channel_dout,
        if_empty_n => img_0_cols_V_channel_empty_n,
        if_read => img_0_cols_V_channel_read);

    img_0_cols_V_channel1_U : component FIFO_sobel_img_0_cols_V_channel1
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_0_cols_V_channel1_U_ap_dummy_ce,
        if_write_ce => img_0_cols_V_channel1_U_ap_dummy_ce,
        if_din => img_0_cols_V_channel1_din,
        if_full_n => img_0_cols_V_channel1_full_n,
        if_write => img_0_cols_V_channel1_write,
        if_dout => img_0_cols_V_channel1_dout,
        if_empty_n => img_0_cols_V_channel1_empty_n,
        if_read => img_0_cols_V_channel1_read);

    img_1_rows_V_U : component FIFO_sobel_img_1_rows_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_1_rows_V_U_ap_dummy_ce,
        if_write_ce => img_1_rows_V_U_ap_dummy_ce,
        if_din => img_1_rows_V_din,
        if_full_n => img_1_rows_V_full_n,
        if_write => img_1_rows_V_write,
        if_dout => img_1_rows_V_dout,
        if_empty_n => img_1_rows_V_empty_n,
        if_read => img_1_rows_V_read);

    img_1_cols_V_U : component FIFO_sobel_img_1_cols_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_1_cols_V_U_ap_dummy_ce,
        if_write_ce => img_1_cols_V_U_ap_dummy_ce,
        if_din => img_1_cols_V_din,
        if_full_n => img_1_cols_V_full_n,
        if_write => img_1_cols_V_write,
        if_dout => img_1_cols_V_dout,
        if_empty_n => img_1_cols_V_empty_n,
        if_read => img_1_cols_V_read);

    img_0_data_stream_0_V_U : component FIFO_sobel_img_0_data_stream_0_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_0_data_stream_0_V_U_ap_dummy_ce,
        if_write_ce => img_0_data_stream_0_V_U_ap_dummy_ce,
        if_din => img_0_data_stream_0_V_din,
        if_full_n => img_0_data_stream_0_V_full_n,
        if_write => img_0_data_stream_0_V_write,
        if_dout => img_0_data_stream_0_V_dout,
        if_empty_n => img_0_data_stream_0_V_empty_n,
        if_read => img_0_data_stream_0_V_read);

    img_0_data_stream_1_V_U : component FIFO_sobel_img_0_data_stream_1_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_0_data_stream_1_V_U_ap_dummy_ce,
        if_write_ce => img_0_data_stream_1_V_U_ap_dummy_ce,
        if_din => img_0_data_stream_1_V_din,
        if_full_n => img_0_data_stream_1_V_full_n,
        if_write => img_0_data_stream_1_V_write,
        if_dout => img_0_data_stream_1_V_dout,
        if_empty_n => img_0_data_stream_1_V_empty_n,
        if_read => img_0_data_stream_1_V_read);

    img_0_data_stream_2_V_U : component FIFO_sobel_img_0_data_stream_2_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_0_data_stream_2_V_U_ap_dummy_ce,
        if_write_ce => img_0_data_stream_2_V_U_ap_dummy_ce,
        if_din => img_0_data_stream_2_V_din,
        if_full_n => img_0_data_stream_2_V_full_n,
        if_write => img_0_data_stream_2_V_write,
        if_dout => img_0_data_stream_2_V_dout,
        if_empty_n => img_0_data_stream_2_V_empty_n,
        if_read => img_0_data_stream_2_V_read);

    img_1_data_stream_0_V_U : component FIFO_sobel_img_1_data_stream_0_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_1_data_stream_0_V_U_ap_dummy_ce,
        if_write_ce => img_1_data_stream_0_V_U_ap_dummy_ce,
        if_din => img_1_data_stream_0_V_din,
        if_full_n => img_1_data_stream_0_V_full_n,
        if_write => img_1_data_stream_0_V_write,
        if_dout => img_1_data_stream_0_V_dout,
        if_empty_n => img_1_data_stream_0_V_empty_n,
        if_read => img_1_data_stream_0_V_read);

    img_1_data_stream_1_V_U : component FIFO_sobel_img_1_data_stream_1_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_1_data_stream_1_V_U_ap_dummy_ce,
        if_write_ce => img_1_data_stream_1_V_U_ap_dummy_ce,
        if_din => img_1_data_stream_1_V_din,
        if_full_n => img_1_data_stream_1_V_full_n,
        if_write => img_1_data_stream_1_V_write,
        if_dout => img_1_data_stream_1_V_dout,
        if_empty_n => img_1_data_stream_1_V_empty_n,
        if_read => img_1_data_stream_1_V_read);

    img_1_data_stream_2_V_U : component FIFO_sobel_img_1_data_stream_2_V
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => img_1_data_stream_2_V_U_ap_dummy_ce,
        if_write_ce => img_1_data_stream_2_V_U_ap_dummy_ce,
        if_din => img_1_data_stream_2_V_din,
        if_full_n => img_1_data_stream_2_V_full_n,
        if_write => img_1_data_stream_2_V_write,
        if_dout => img_1_data_stream_2_V_dout,
        if_empty_n => img_1_data_stream_2_V_empty_n,
        if_read => img_1_data_stream_2_V_read);





    -- ap_reg_procdone_sobel_AXIvideo2Mat_U0 assign process. --
    ap_reg_procdone_sobel_AXIvideo2Mat_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_sobel_AXIvideo2Mat_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_sobel_AXIvideo2Mat_U0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = sobel_AXIvideo2Mat_U0_ap_done)) then 
                    ap_reg_procdone_sobel_AXIvideo2Mat_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_procdone_sobel_Block_proc_U0 assign process. --
    ap_reg_procdone_sobel_Block_proc_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_sobel_Block_proc_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_sobel_Block_proc_U0 <= ap_const_logic_0;
                elsif ((sobel_Block_proc_U0_ap_done = ap_const_logic_1)) then 
                    ap_reg_procdone_sobel_Block_proc_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_procdone_sobel_Mat2AXIvideo_U0 assign process. --
    ap_reg_procdone_sobel_Mat2AXIvideo_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_sobel_Mat2AXIvideo_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_sobel_Mat2AXIvideo_U0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = sobel_Mat2AXIvideo_U0_ap_done)) then 
                    ap_reg_procdone_sobel_Mat2AXIvideo_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_procdone_sobel_Sobel_U0 assign process. --
    ap_reg_procdone_sobel_Sobel_U0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_procdone_sobel_Sobel_U0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_sig_hs_done)) then 
                    ap_reg_procdone_sobel_Sobel_U0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = sobel_Sobel_U0_ap_done)) then 
                    ap_reg_procdone_sobel_Sobel_U0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_img_0_cols_V_channel1_full_n assign process. --
    ap_reg_ready_img_0_cols_V_channel1_full_n_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_img_0_cols_V_channel1_full_n <= ap_const_logic_0;
            else
                if (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (sobel_Block_proc_U0_ap_continue = ap_const_logic_1))) then 
                    ap_reg_ready_img_0_cols_V_channel1_full_n <= ap_const_logic_0;
                elsif (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (ap_const_logic_1 = img_0_cols_V_channel1_full_n))) then 
                    ap_reg_ready_img_0_cols_V_channel1_full_n <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_img_0_cols_V_channel_full_n assign process. --
    ap_reg_ready_img_0_cols_V_channel_full_n_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_img_0_cols_V_channel_full_n <= ap_const_logic_0;
            else
                if (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (sobel_Block_proc_U0_ap_continue = ap_const_logic_1))) then 
                    ap_reg_ready_img_0_cols_V_channel_full_n <= ap_const_logic_0;
                elsif (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (ap_const_logic_1 = img_0_cols_V_channel_full_n))) then 
                    ap_reg_ready_img_0_cols_V_channel_full_n <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_img_0_rows_V_channel1_full_n assign process. --
    ap_reg_ready_img_0_rows_V_channel1_full_n_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_img_0_rows_V_channel1_full_n <= ap_const_logic_0;
            else
                if (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (sobel_Block_proc_U0_ap_continue = ap_const_logic_1))) then 
                    ap_reg_ready_img_0_rows_V_channel1_full_n <= ap_const_logic_0;
                elsif (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (ap_const_logic_1 = img_0_rows_V_channel1_full_n))) then 
                    ap_reg_ready_img_0_rows_V_channel1_full_n <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_img_0_rows_V_channel_full_n assign process. --
    ap_reg_ready_img_0_rows_V_channel_full_n_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_img_0_rows_V_channel_full_n <= ap_const_logic_0;
            else
                if (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (sobel_Block_proc_U0_ap_continue = ap_const_logic_1))) then 
                    ap_reg_ready_img_0_rows_V_channel_full_n <= ap_const_logic_0;
                elsif (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (img_0_rows_V_channel_full_n = ap_const_logic_1))) then 
                    ap_reg_ready_img_0_rows_V_channel_full_n <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_img_1_cols_V_full_n assign process. --
    ap_reg_ready_img_1_cols_V_full_n_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_img_1_cols_V_full_n <= ap_const_logic_0;
            else
                if (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (sobel_Block_proc_U0_ap_continue = ap_const_logic_1))) then 
                    ap_reg_ready_img_1_cols_V_full_n <= ap_const_logic_0;
                elsif (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (ap_const_logic_1 = img_1_cols_V_full_n))) then 
                    ap_reg_ready_img_1_cols_V_full_n <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_reg_ready_img_1_rows_V_full_n assign process. --
    ap_reg_ready_img_1_rows_V_full_n_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_reg_ready_img_1_rows_V_full_n <= ap_const_logic_0;
            else
                if (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (sobel_Block_proc_U0_ap_continue = ap_const_logic_1))) then 
                    ap_reg_ready_img_1_rows_V_full_n <= ap_const_logic_0;
                elsif (((sobel_Block_proc_U0_ap_done = ap_const_logic_1) and (ap_const_logic_1 = img_1_rows_V_full_n))) then 
                    ap_reg_ready_img_1_rows_V_full_n <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    -- ap_CS assign process. --
    ap_CS_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_CS <= ap_const_logic_0;
        end if;
    end process;
    INPUT_STREAM_TREADY <= sobel_AXIvideo2Mat_U0_INPUT_STREAM_TREADY;
    OUTPUT_STREAM_TDATA <= sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA;
    OUTPUT_STREAM_TDEST <= sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST;
    OUTPUT_STREAM_TID <= sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TID;
    OUTPUT_STREAM_TKEEP <= sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP;
    OUTPUT_STREAM_TLAST <= sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST;
    OUTPUT_STREAM_TSTRB <= sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB;
    OUTPUT_STREAM_TUSER <= sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER;
    OUTPUT_STREAM_TVALID <= sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID;

    -- ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel assign process. --
    ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel_assign_proc : process(sobel_Block_proc_U0_ap_done, ap_reg_ready_img_0_cols_V_channel_full_n)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_img_0_cols_V_channel_full_n)) then 
            ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel <= ap_const_logic_0;
        else 
            ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel <= sobel_Block_proc_U0_ap_done;
        end if; 
    end process;


    -- ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel1 assign process. --
    ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel1_assign_proc : process(sobel_Block_proc_U0_ap_done, ap_reg_ready_img_0_cols_V_channel1_full_n)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_img_0_cols_V_channel1_full_n)) then 
            ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel1 <= ap_const_logic_0;
        else 
            ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel1 <= sobel_Block_proc_U0_ap_done;
        end if; 
    end process;


    -- ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel assign process. --
    ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel_assign_proc : process(sobel_Block_proc_U0_ap_done, ap_reg_ready_img_0_rows_V_channel_full_n)
    begin
        if ((ap_reg_ready_img_0_rows_V_channel_full_n = ap_const_logic_1)) then 
            ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel <= ap_const_logic_0;
        else 
            ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel <= sobel_Block_proc_U0_ap_done;
        end if; 
    end process;


    -- ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel1 assign process. --
    ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel1_assign_proc : process(sobel_Block_proc_U0_ap_done, ap_reg_ready_img_0_rows_V_channel1_full_n)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_img_0_rows_V_channel1_full_n)) then 
            ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel1 <= ap_const_logic_0;
        else 
            ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel1 <= sobel_Block_proc_U0_ap_done;
        end if; 
    end process;


    -- ap_chn_write_sobel_Block_proc_U0_img_1_cols_V assign process. --
    ap_chn_write_sobel_Block_proc_U0_img_1_cols_V_assign_proc : process(sobel_Block_proc_U0_ap_done, ap_reg_ready_img_1_cols_V_full_n)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_img_1_cols_V_full_n)) then 
            ap_chn_write_sobel_Block_proc_U0_img_1_cols_V <= ap_const_logic_0;
        else 
            ap_chn_write_sobel_Block_proc_U0_img_1_cols_V <= sobel_Block_proc_U0_ap_done;
        end if; 
    end process;


    -- ap_chn_write_sobel_Block_proc_U0_img_1_rows_V assign process. --
    ap_chn_write_sobel_Block_proc_U0_img_1_rows_V_assign_proc : process(sobel_Block_proc_U0_ap_done, ap_reg_ready_img_1_rows_V_full_n)
    begin
        if ((ap_const_logic_1 = ap_reg_ready_img_1_rows_V_full_n)) then 
            ap_chn_write_sobel_Block_proc_U0_img_1_rows_V <= ap_const_logic_0;
        else 
            ap_chn_write_sobel_Block_proc_U0_img_1_rows_V <= sobel_Block_proc_U0_ap_done;
        end if; 
    end process;

    ap_done <= ap_sig_hs_done;

    -- ap_idle assign process. --
    ap_idle_assign_proc : process(sobel_Block_proc_U0_ap_idle, sobel_AXIvideo2Mat_U0_ap_idle, sobel_Sobel_U0_ap_idle, sobel_Mat2AXIvideo_U0_ap_idle, img_0_rows_V_channel_empty_n, img_0_rows_V_channel1_empty_n, img_0_cols_V_channel_empty_n, img_0_cols_V_channel1_empty_n, img_1_rows_V_empty_n, img_1_cols_V_empty_n)
    begin
        if (((sobel_Block_proc_U0_ap_idle = ap_const_logic_1) and (ap_const_logic_1 = sobel_AXIvideo2Mat_U0_ap_idle) and (ap_const_logic_1 = sobel_Sobel_U0_ap_idle) and (ap_const_logic_1 = sobel_Mat2AXIvideo_U0_ap_idle) and (ap_const_logic_0 = img_0_rows_V_channel_empty_n) and (ap_const_logic_0 = img_0_rows_V_channel1_empty_n) and (ap_const_logic_0 = img_0_cols_V_channel_empty_n) and (ap_const_logic_0 = img_0_cols_V_channel1_empty_n) and (ap_const_logic_0 = img_1_rows_V_empty_n) and (ap_const_logic_0 = img_1_cols_V_empty_n))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= ap_sig_top_allready;

    -- ap_rst_n_inv assign process. --
    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sig_hs_continue <= ap_const_logic_1;

    -- ap_sig_hs_done assign process. --
    ap_sig_hs_done_assign_proc : process(sobel_Mat2AXIvideo_U0_ap_done)
    begin
        if ((ap_const_logic_1 = sobel_Mat2AXIvideo_U0_ap_done)) then 
            ap_sig_hs_done <= ap_const_logic_1;
        else 
            ap_sig_hs_done <= ap_const_logic_0;
        end if; 
    end process;


    -- ap_sig_ready_img_0_cols_V_channel1_full_n assign process. --
    ap_sig_ready_img_0_cols_V_channel1_full_n_assign_proc : process(img_0_cols_V_channel1_full_n, ap_reg_ready_img_0_cols_V_channel1_full_n)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_img_0_cols_V_channel1_full_n)) then 
            ap_sig_ready_img_0_cols_V_channel1_full_n <= img_0_cols_V_channel1_full_n;
        else 
            ap_sig_ready_img_0_cols_V_channel1_full_n <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_img_0_cols_V_channel_full_n assign process. --
    ap_sig_ready_img_0_cols_V_channel_full_n_assign_proc : process(img_0_cols_V_channel_full_n, ap_reg_ready_img_0_cols_V_channel_full_n)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_img_0_cols_V_channel_full_n)) then 
            ap_sig_ready_img_0_cols_V_channel_full_n <= img_0_cols_V_channel_full_n;
        else 
            ap_sig_ready_img_0_cols_V_channel_full_n <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_img_0_rows_V_channel1_full_n assign process. --
    ap_sig_ready_img_0_rows_V_channel1_full_n_assign_proc : process(img_0_rows_V_channel1_full_n, ap_reg_ready_img_0_rows_V_channel1_full_n)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_img_0_rows_V_channel1_full_n)) then 
            ap_sig_ready_img_0_rows_V_channel1_full_n <= img_0_rows_V_channel1_full_n;
        else 
            ap_sig_ready_img_0_rows_V_channel1_full_n <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_img_0_rows_V_channel_full_n assign process. --
    ap_sig_ready_img_0_rows_V_channel_full_n_assign_proc : process(img_0_rows_V_channel_full_n, ap_reg_ready_img_0_rows_V_channel_full_n)
    begin
        if ((ap_reg_ready_img_0_rows_V_channel_full_n = ap_const_logic_0)) then 
            ap_sig_ready_img_0_rows_V_channel_full_n <= img_0_rows_V_channel_full_n;
        else 
            ap_sig_ready_img_0_rows_V_channel_full_n <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_img_1_cols_V_full_n assign process. --
    ap_sig_ready_img_1_cols_V_full_n_assign_proc : process(img_1_cols_V_full_n, ap_reg_ready_img_1_cols_V_full_n)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_img_1_cols_V_full_n)) then 
            ap_sig_ready_img_1_cols_V_full_n <= img_1_cols_V_full_n;
        else 
            ap_sig_ready_img_1_cols_V_full_n <= ap_const_logic_1;
        end if; 
    end process;


    -- ap_sig_ready_img_1_rows_V_full_n assign process. --
    ap_sig_ready_img_1_rows_V_full_n_assign_proc : process(img_1_rows_V_full_n, ap_reg_ready_img_1_rows_V_full_n)
    begin
        if ((ap_const_logic_0 = ap_reg_ready_img_1_rows_V_full_n)) then 
            ap_sig_ready_img_1_rows_V_full_n <= img_1_rows_V_full_n;
        else 
            ap_sig_ready_img_1_rows_V_full_n <= ap_const_logic_1;
        end if; 
    end process;

    ap_sig_top_allready <= sobel_AXIvideo2Mat_U0_ap_ready;
    img_0_cols_V_channel1_U_ap_dummy_ce <= ap_const_logic_1;
    img_0_cols_V_channel1_din <= sobel_Block_proc_U0_ap_return_3;
    img_0_cols_V_channel1_read <= sobel_Sobel_U0_ap_ready;
    img_0_cols_V_channel1_write <= ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel1;
    img_0_cols_V_channel_U_ap_dummy_ce <= ap_const_logic_1;
    img_0_cols_V_channel_din <= sobel_Block_proc_U0_ap_return_2;
    img_0_cols_V_channel_read <= sobel_AXIvideo2Mat_U0_ap_ready;
    img_0_cols_V_channel_write <= ap_chn_write_sobel_Block_proc_U0_img_0_cols_V_channel;
    img_0_data_stream_0_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_0_data_stream_0_V_din <= sobel_AXIvideo2Mat_U0_img_data_stream_0_V_din;
    img_0_data_stream_0_V_read <= sobel_Sobel_U0_p_src_data_stream_0_V_read;
    img_0_data_stream_0_V_write <= sobel_AXIvideo2Mat_U0_img_data_stream_0_V_write;
    img_0_data_stream_1_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_0_data_stream_1_V_din <= sobel_AXIvideo2Mat_U0_img_data_stream_1_V_din;
    img_0_data_stream_1_V_read <= sobel_Sobel_U0_p_src_data_stream_1_V_read;
    img_0_data_stream_1_V_write <= sobel_AXIvideo2Mat_U0_img_data_stream_1_V_write;
    img_0_data_stream_2_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_0_data_stream_2_V_din <= sobel_AXIvideo2Mat_U0_img_data_stream_2_V_din;
    img_0_data_stream_2_V_read <= sobel_Sobel_U0_p_src_data_stream_2_V_read;
    img_0_data_stream_2_V_write <= sobel_AXIvideo2Mat_U0_img_data_stream_2_V_write;
    img_0_rows_V_channel1_U_ap_dummy_ce <= ap_const_logic_1;
    img_0_rows_V_channel1_din <= sobel_Block_proc_U0_ap_return_1;
    img_0_rows_V_channel1_read <= sobel_Sobel_U0_ap_ready;
    img_0_rows_V_channel1_write <= ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel1;
    img_0_rows_V_channel_U_ap_dummy_ce <= ap_const_logic_1;
    img_0_rows_V_channel_din <= sobel_Block_proc_U0_ap_return_0;
    img_0_rows_V_channel_read <= sobel_AXIvideo2Mat_U0_ap_ready;
    img_0_rows_V_channel_write <= ap_chn_write_sobel_Block_proc_U0_img_0_rows_V_channel;
    img_1_cols_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_1_cols_V_din <= sobel_Block_proc_U0_ap_return_5;
    img_1_cols_V_read <= sobel_Mat2AXIvideo_U0_ap_ready;
    img_1_cols_V_write <= ap_chn_write_sobel_Block_proc_U0_img_1_cols_V;
    img_1_data_stream_0_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_1_data_stream_0_V_din <= sobel_Sobel_U0_p_dst_data_stream_0_V_din;
    img_1_data_stream_0_V_read <= sobel_Mat2AXIvideo_U0_img_data_stream_0_V_read;
    img_1_data_stream_0_V_write <= sobel_Sobel_U0_p_dst_data_stream_0_V_write;
    img_1_data_stream_1_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_1_data_stream_1_V_din <= sobel_Sobel_U0_p_dst_data_stream_1_V_din;
    img_1_data_stream_1_V_read <= sobel_Mat2AXIvideo_U0_img_data_stream_1_V_read;
    img_1_data_stream_1_V_write <= sobel_Sobel_U0_p_dst_data_stream_1_V_write;
    img_1_data_stream_2_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_1_data_stream_2_V_din <= sobel_Sobel_U0_p_dst_data_stream_2_V_din;
    img_1_data_stream_2_V_read <= sobel_Mat2AXIvideo_U0_img_data_stream_2_V_read;
    img_1_data_stream_2_V_write <= sobel_Sobel_U0_p_dst_data_stream_2_V_write;
    img_1_rows_V_U_ap_dummy_ce <= ap_const_logic_1;
    img_1_rows_V_din <= sobel_Block_proc_U0_ap_return_4;
    img_1_rows_V_read <= sobel_Mat2AXIvideo_U0_ap_ready;
    img_1_rows_V_write <= ap_chn_write_sobel_Block_proc_U0_img_1_rows_V;
    sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDATA <= INPUT_STREAM_TDATA;
    sobel_AXIvideo2Mat_U0_INPUT_STREAM_TDEST <= INPUT_STREAM_TDEST;
    sobel_AXIvideo2Mat_U0_INPUT_STREAM_TID <= INPUT_STREAM_TID;
    sobel_AXIvideo2Mat_U0_INPUT_STREAM_TKEEP <= INPUT_STREAM_TKEEP;
    sobel_AXIvideo2Mat_U0_INPUT_STREAM_TLAST <= INPUT_STREAM_TLAST;
    sobel_AXIvideo2Mat_U0_INPUT_STREAM_TSTRB <= INPUT_STREAM_TSTRB;
    sobel_AXIvideo2Mat_U0_INPUT_STREAM_TUSER <= INPUT_STREAM_TUSER;
    sobel_AXIvideo2Mat_U0_INPUT_STREAM_TVALID <= INPUT_STREAM_TVALID;
    sobel_AXIvideo2Mat_U0_ap_continue <= ap_const_logic_1;
    sobel_AXIvideo2Mat_U0_ap_start <= (ap_start and img_0_rows_V_channel_empty_n and img_0_cols_V_channel_empty_n);
    sobel_AXIvideo2Mat_U0_img_cols_V_read <= img_0_cols_V_channel_dout;
    sobel_AXIvideo2Mat_U0_img_data_stream_0_V_full_n <= img_0_data_stream_0_V_full_n;
    sobel_AXIvideo2Mat_U0_img_data_stream_1_V_full_n <= img_0_data_stream_1_V_full_n;
    sobel_AXIvideo2Mat_U0_img_data_stream_2_V_full_n <= img_0_data_stream_2_V_full_n;
    sobel_AXIvideo2Mat_U0_img_rows_V_read <= img_0_rows_V_channel_dout;

    -- sobel_Block_proc_U0_ap_continue assign process. --
    sobel_Block_proc_U0_ap_continue_assign_proc : process(ap_sig_ready_img_0_rows_V_channel_full_n, ap_sig_ready_img_0_cols_V_channel_full_n, ap_sig_ready_img_1_cols_V_full_n, ap_sig_ready_img_1_rows_V_full_n, ap_sig_ready_img_0_rows_V_channel1_full_n, ap_sig_ready_img_0_cols_V_channel1_full_n)
    begin
        if (((ap_sig_ready_img_0_rows_V_channel_full_n = ap_const_logic_1) and (ap_const_logic_1 = ap_sig_ready_img_0_cols_V_channel_full_n) and (ap_const_logic_1 = ap_sig_ready_img_1_cols_V_full_n) and (ap_const_logic_1 = ap_sig_ready_img_1_rows_V_full_n) and (ap_const_logic_1 = ap_sig_ready_img_0_rows_V_channel1_full_n) and (ap_const_logic_1 = ap_sig_ready_img_0_cols_V_channel1_full_n))) then 
            sobel_Block_proc_U0_ap_continue <= ap_const_logic_1;
        else 
            sobel_Block_proc_U0_ap_continue <= ap_const_logic_0;
        end if; 
    end process;

    sobel_Block_proc_U0_ap_start <= ap_start;
    sobel_Block_proc_U0_cols <= cols;
    sobel_Block_proc_U0_rows <= rows;
    sobel_Mat2AXIvideo_U0_OUTPUT_STREAM_TREADY <= OUTPUT_STREAM_TREADY;
    sobel_Mat2AXIvideo_U0_ap_continue <= ap_sig_hs_continue;
    sobel_Mat2AXIvideo_U0_ap_start <= (img_1_rows_V_empty_n and img_1_cols_V_empty_n);
    sobel_Mat2AXIvideo_U0_img_cols_V_read <= img_1_cols_V_dout;
    sobel_Mat2AXIvideo_U0_img_data_stream_0_V_dout <= img_1_data_stream_0_V_dout;
    sobel_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n <= img_1_data_stream_0_V_empty_n;
    sobel_Mat2AXIvideo_U0_img_data_stream_1_V_dout <= img_1_data_stream_1_V_dout;
    sobel_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n <= img_1_data_stream_1_V_empty_n;
    sobel_Mat2AXIvideo_U0_img_data_stream_2_V_dout <= img_1_data_stream_2_V_dout;
    sobel_Mat2AXIvideo_U0_img_data_stream_2_V_empty_n <= img_1_data_stream_2_V_empty_n;
    sobel_Mat2AXIvideo_U0_img_rows_V_read <= img_1_rows_V_dout;
    sobel_Sobel_U0_ap_continue <= ap_const_logic_1;
    sobel_Sobel_U0_ap_start <= (img_0_rows_V_channel1_empty_n and img_0_cols_V_channel1_empty_n);
    sobel_Sobel_U0_p_dst_data_stream_0_V_full_n <= img_1_data_stream_0_V_full_n;
    sobel_Sobel_U0_p_dst_data_stream_1_V_full_n <= img_1_data_stream_1_V_full_n;
    sobel_Sobel_U0_p_dst_data_stream_2_V_full_n <= img_1_data_stream_2_V_full_n;
    sobel_Sobel_U0_p_src_cols_V_read <= img_0_cols_V_channel1_dout;
    sobel_Sobel_U0_p_src_data_stream_0_V_dout <= img_0_data_stream_0_V_dout;
    sobel_Sobel_U0_p_src_data_stream_0_V_empty_n <= img_0_data_stream_0_V_empty_n;
    sobel_Sobel_U0_p_src_data_stream_1_V_dout <= img_0_data_stream_1_V_dout;
    sobel_Sobel_U0_p_src_data_stream_1_V_empty_n <= img_0_data_stream_1_V_empty_n;
    sobel_Sobel_U0_p_src_data_stream_2_V_dout <= img_0_data_stream_2_V_dout;
    sobel_Sobel_U0_p_src_data_stream_2_V_empty_n <= img_0_data_stream_2_V_empty_n;
    sobel_Sobel_U0_p_src_rows_V_read <= img_0_rows_V_channel1_dout;
end behav;
