// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _sobel_Mat2AXIvideo_HH_
#define _sobel_Mat2AXIvideo_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct sobel_Mat2AXIvideo : public sc_module {
    // Port declarations 27
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<12> > img_rows_V_read;
    sc_in< sc_lv<12> > img_cols_V_read;
    sc_in< sc_lv<8> > img_data_stream_0_V_dout;
    sc_in< sc_logic > img_data_stream_0_V_empty_n;
    sc_out< sc_logic > img_data_stream_0_V_read;
    sc_in< sc_lv<8> > img_data_stream_1_V_dout;
    sc_in< sc_logic > img_data_stream_1_V_empty_n;
    sc_out< sc_logic > img_data_stream_1_V_read;
    sc_in< sc_lv<8> > img_data_stream_2_V_dout;
    sc_in< sc_logic > img_data_stream_2_V_empty_n;
    sc_out< sc_logic > img_data_stream_2_V_read;
    sc_out< sc_lv<32> > OUTPUT_STREAM_TDATA;
    sc_out< sc_logic > OUTPUT_STREAM_TVALID;
    sc_in< sc_logic > OUTPUT_STREAM_TREADY;
    sc_out< sc_lv<4> > OUTPUT_STREAM_TKEEP;
    sc_out< sc_lv<4> > OUTPUT_STREAM_TSTRB;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TUSER;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TLAST;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TID;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TDEST;


    // Module declarations
    sobel_Mat2AXIvideo(sc_module_name name);
    SC_HAS_PROCESS(sobel_Mat2AXIvideo);

    ~sobel_Mat2AXIvideo();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_23;
    sc_signal< sc_lv<12> > p_3_reg_170;
    sc_signal< bool > ap_sig_bdd_60;
    sc_signal< sc_lv<13> > op2_assign_fu_186_p2;
    sc_signal< sc_lv<13> > op2_assign_reg_267;
    sc_signal< sc_lv<1> > exitcond3_fu_197_p2;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_74;
    sc_signal< sc_lv<12> > i_V_fu_202_p2;
    sc_signal< sc_lv<12> > i_V_reg_276;
    sc_signal< sc_lv<1> > exitcond4_fu_208_p2;
    sc_signal< sc_lv<1> > exitcond4_reg_281;
    sc_signal< sc_logic > ap_sig_cseq_ST_pp0_stg0_fsm_2;
    sc_signal< bool > ap_sig_bdd_85;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it0;
    sc_signal< bool > ap_sig_bdd_99;
    sc_signal< sc_logic > ap_sig_ioackin_OUTPUT_STREAM_TREADY;
    sc_signal< sc_logic > ap_reg_ppiten_pp0_it1;
    sc_signal< sc_lv<12> > j_V_fu_213_p2;
    sc_signal< sc_lv<1> > axi_last_V_fu_223_p2;
    sc_signal< sc_lv<1> > axi_last_V_reg_290;
    sc_signal< sc_lv<12> > p_s_reg_159;
    sc_signal< sc_logic > ap_sig_cseq_ST_st5_fsm_3;
    sc_signal< bool > ap_sig_bdd_130;
    sc_signal< sc_lv<1> > tmp_user_V_fu_96;
    sc_signal< sc_logic > ap_reg_ioackin_OUTPUT_STREAM_TREADY;
    sc_signal< sc_lv<13> > tmp_cast_fu_182_p1;
    sc_signal< sc_lv<13> > tmp_cast_54_fu_219_p1;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_st1_fsm_0;
    static const sc_lv<4> ap_ST_st2_fsm_1;
    static const sc_lv<4> ap_ST_pp0_stg0_fsm_2;
    static const sc_lv<4> ap_ST_st5_fsm_3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<12> ap_const_lv12_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<4> ap_const_lv4_F;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<13> ap_const_lv13_1FFF;
    static const sc_lv<12> ap_const_lv12_1;
    static const sc_lv<8> ap_const_lv8_FF;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_OUTPUT_STREAM_TDATA();
    void thread_OUTPUT_STREAM_TDEST();
    void thread_OUTPUT_STREAM_TID();
    void thread_OUTPUT_STREAM_TKEEP();
    void thread_OUTPUT_STREAM_TLAST();
    void thread_OUTPUT_STREAM_TSTRB();
    void thread_OUTPUT_STREAM_TUSER();
    void thread_OUTPUT_STREAM_TVALID();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_130();
    void thread_ap_sig_bdd_23();
    void thread_ap_sig_bdd_60();
    void thread_ap_sig_bdd_74();
    void thread_ap_sig_bdd_85();
    void thread_ap_sig_bdd_99();
    void thread_ap_sig_cseq_ST_pp0_stg0_fsm_2();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_ap_sig_cseq_ST_st5_fsm_3();
    void thread_ap_sig_ioackin_OUTPUT_STREAM_TREADY();
    void thread_axi_last_V_fu_223_p2();
    void thread_exitcond3_fu_197_p2();
    void thread_exitcond4_fu_208_p2();
    void thread_i_V_fu_202_p2();
    void thread_img_data_stream_0_V_read();
    void thread_img_data_stream_1_V_read();
    void thread_img_data_stream_2_V_read();
    void thread_j_V_fu_213_p2();
    void thread_op2_assign_fu_186_p2();
    void thread_tmp_cast_54_fu_219_p1();
    void thread_tmp_cast_fu_182_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
