// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "sobel_Sobel.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic sobel_Sobel::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic sobel_Sobel::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> sobel_Sobel::ap_ST_st1_fsm_0 = "1";
const sc_lv<2> sobel_Sobel::ap_ST_st2_fsm_1 = "10";
const sc_lv<32> sobel_Sobel::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> sobel_Sobel::ap_const_lv1_1 = "1";
const sc_lv<32> sobel_Sobel::ap_const_lv32_1 = "1";

sobel_Sobel::sobel_Sobel(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_sobel_Filter2D_fu_61 = new sobel_Filter2D("grp_sobel_Filter2D_fu_61");
    grp_sobel_Filter2D_fu_61->ap_clk(ap_clk);
    grp_sobel_Filter2D_fu_61->ap_rst(ap_rst);
    grp_sobel_Filter2D_fu_61->ap_start(grp_sobel_Filter2D_fu_61_ap_start);
    grp_sobel_Filter2D_fu_61->ap_done(grp_sobel_Filter2D_fu_61_ap_done);
    grp_sobel_Filter2D_fu_61->ap_idle(grp_sobel_Filter2D_fu_61_ap_idle);
    grp_sobel_Filter2D_fu_61->ap_ready(grp_sobel_Filter2D_fu_61_ap_ready);
    grp_sobel_Filter2D_fu_61->p_src_rows_V_read(grp_sobel_Filter2D_fu_61_p_src_rows_V_read);
    grp_sobel_Filter2D_fu_61->p_src_cols_V_read(grp_sobel_Filter2D_fu_61_p_src_cols_V_read);
    grp_sobel_Filter2D_fu_61->p_src_data_stream_0_V_dout(grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_dout);
    grp_sobel_Filter2D_fu_61->p_src_data_stream_0_V_empty_n(grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_empty_n);
    grp_sobel_Filter2D_fu_61->p_src_data_stream_0_V_read(grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_read);
    grp_sobel_Filter2D_fu_61->p_src_data_stream_1_V_dout(grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_dout);
    grp_sobel_Filter2D_fu_61->p_src_data_stream_1_V_empty_n(grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_empty_n);
    grp_sobel_Filter2D_fu_61->p_src_data_stream_1_V_read(grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_read);
    grp_sobel_Filter2D_fu_61->p_src_data_stream_2_V_dout(grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_dout);
    grp_sobel_Filter2D_fu_61->p_src_data_stream_2_V_empty_n(grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_empty_n);
    grp_sobel_Filter2D_fu_61->p_src_data_stream_2_V_read(grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_read);
    grp_sobel_Filter2D_fu_61->p_dst_data_stream_0_V_din(grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_din);
    grp_sobel_Filter2D_fu_61->p_dst_data_stream_0_V_full_n(grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_full_n);
    grp_sobel_Filter2D_fu_61->p_dst_data_stream_0_V_write(grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_write);
    grp_sobel_Filter2D_fu_61->p_dst_data_stream_1_V_din(grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_din);
    grp_sobel_Filter2D_fu_61->p_dst_data_stream_1_V_full_n(grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_full_n);
    grp_sobel_Filter2D_fu_61->p_dst_data_stream_1_V_write(grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_write);
    grp_sobel_Filter2D_fu_61->p_dst_data_stream_2_V_din(grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_din);
    grp_sobel_Filter2D_fu_61->p_dst_data_stream_2_V_full_n(grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_full_n);
    grp_sobel_Filter2D_fu_61->p_dst_data_stream_2_V_write(grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_write);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( grp_sobel_Filter2D_fu_61_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_sobel_Filter2D_fu_61_ap_done );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_bdd_21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_bdd_59);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_sig_bdd_97);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_bdd_21 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_bdd_97 );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_ap_start);
    sensitive << ( grp_sobel_Filter2D_fu_61_ap_start_ap_start_reg );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_full_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( p_dst_data_stream_0_V_full_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_full_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( p_dst_data_stream_1_V_full_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_full_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( p_dst_data_stream_2_V_full_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_p_src_cols_V_read);
    sensitive << ( p_src_cols_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_dout);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( p_src_data_stream_0_V_dout );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_empty_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( p_src_data_stream_0_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_dout);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( p_src_data_stream_1_V_dout );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_empty_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( p_src_data_stream_1_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_dout);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( p_src_data_stream_2_V_dout );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_empty_n);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( p_src_data_stream_2_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_grp_sobel_Filter2D_fu_61_p_src_rows_V_read);
    sensitive << ( p_src_rows_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_dst_data_stream_0_V_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_din );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_dst_data_stream_0_V_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_write );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_dst_data_stream_1_V_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_din );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_dst_data_stream_1_V_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_write );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_dst_data_stream_2_V_din);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_din );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_dst_data_stream_2_V_write);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_write );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_src_data_stream_0_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_src_data_stream_1_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_p_src_data_stream_2_V_read);
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_read );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_sig_bdd_59 );
    sensitive << ( grp_sobel_Filter2D_fu_61_ap_done );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    grp_sobel_Filter2D_fu_61_ap_start_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sobel_Sobel_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_src_rows_V_read, "(port)p_src_rows_V_read");
    sc_trace(mVcdFile, p_src_cols_V_read, "(port)p_src_cols_V_read");
    sc_trace(mVcdFile, p_src_data_stream_0_V_dout, "(port)p_src_data_stream_0_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_0_V_empty_n, "(port)p_src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_0_V_read, "(port)p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, p_src_data_stream_1_V_dout, "(port)p_src_data_stream_1_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_1_V_empty_n, "(port)p_src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_1_V_read, "(port)p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, p_src_data_stream_2_V_dout, "(port)p_src_data_stream_2_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_2_V_empty_n, "(port)p_src_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_2_V_read, "(port)p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_0_V_din, "(port)p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_0_V_full_n, "(port)p_dst_data_stream_0_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_0_V_write, "(port)p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, p_dst_data_stream_1_V_din, "(port)p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_1_V_full_n, "(port)p_dst_data_stream_1_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_1_V_write, "(port)p_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, p_dst_data_stream_2_V_din, "(port)p_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_2_V_full_n, "(port)p_dst_data_stream_2_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_2_V_write, "(port)p_dst_data_stream_2_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_bdd_21, "ap_sig_bdd_21");
    sc_trace(mVcdFile, ap_sig_bdd_59, "ap_sig_bdd_59");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_ap_start, "grp_sobel_Filter2D_fu_61_ap_start");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_ap_done, "grp_sobel_Filter2D_fu_61_ap_done");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_ap_idle, "grp_sobel_Filter2D_fu_61_ap_idle");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_ap_ready, "grp_sobel_Filter2D_fu_61_ap_ready");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_src_rows_V_read, "grp_sobel_Filter2D_fu_61_p_src_rows_V_read");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_src_cols_V_read, "grp_sobel_Filter2D_fu_61_p_src_cols_V_read");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_dout, "grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_dout");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_empty_n, "grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_read, "grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_dout, "grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_dout");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_empty_n, "grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_read, "grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_dout, "grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_dout");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_empty_n, "grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_read, "grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_din, "grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_full_n, "grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_full_n");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_write, "grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_din, "grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_full_n, "grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_full_n");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_write, "grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_din, "grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_full_n, "grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_full_n");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_write, "grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_write");
    sc_trace(mVcdFile, grp_sobel_Filter2D_fu_61_ap_start_ap_start_reg, "grp_sobel_Filter2D_fu_61_ap_start_ap_start_reg");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_bdd_97, "ap_sig_bdd_97");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

sobel_Sobel::~sobel_Sobel() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_sobel_Filter2D_fu_61;
}

void sobel_Sobel::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    !esl_seteq<1,1,1>(ap_const_logic_0, grp_sobel_Filter2D_fu_61_ap_done.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_sobel_Filter2D_fu_61_ap_start_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
             !ap_sig_bdd_59.read())) {
            grp_sobel_Filter2D_fu_61_ap_start_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sobel_Filter2D_fu_61_ap_ready.read())) {
            grp_sobel_Filter2D_fu_61_ap_start_ap_start_reg = ap_const_logic_0;
        }
    }
}

void sobel_Sobel::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_done_reg.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_logic_0, grp_sobel_Filter2D_fu_61_ap_done.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void sobel_Sobel::thread_ap_idle() {
    if ((!esl_seteq<1,1,1>(ap_const_logic_1, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void sobel_Sobel::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_logic_0, grp_sobel_Filter2D_fu_61_ap_done.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void sobel_Sobel::thread_ap_sig_bdd_21() {
    ap_sig_bdd_21 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void sobel_Sobel::thread_ap_sig_bdd_59() {
    ap_sig_bdd_59 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void sobel_Sobel::thread_ap_sig_bdd_97() {
    ap_sig_bdd_97 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void sobel_Sobel::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_bdd_21.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void sobel_Sobel::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_bdd_97.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_ap_start() {
    grp_sobel_Filter2D_fu_61_ap_start = grp_sobel_Filter2D_fu_61_ap_start_ap_start_reg.read();
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_full_n() {
    grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_full_n = p_dst_data_stream_0_V_full_n.read();
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_full_n() {
    grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_full_n = p_dst_data_stream_1_V_full_n.read();
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_full_n() {
    grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_full_n = p_dst_data_stream_2_V_full_n.read();
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_p_src_cols_V_read() {
    grp_sobel_Filter2D_fu_61_p_src_cols_V_read = p_src_cols_V_read.read();
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_dout() {
    grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_dout = p_src_data_stream_0_V_dout.read();
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_empty_n() {
    grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_empty_n = p_src_data_stream_0_V_empty_n.read();
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_dout() {
    grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_dout = p_src_data_stream_1_V_dout.read();
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_empty_n() {
    grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_empty_n = p_src_data_stream_1_V_empty_n.read();
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_dout() {
    grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_dout = p_src_data_stream_2_V_dout.read();
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_empty_n() {
    grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_empty_n = p_src_data_stream_2_V_empty_n.read();
}

void sobel_Sobel::thread_grp_sobel_Filter2D_fu_61_p_src_rows_V_read() {
    grp_sobel_Filter2D_fu_61_p_src_rows_V_read = p_src_rows_V_read.read();
}

void sobel_Sobel::thread_p_dst_data_stream_0_V_din() {
    p_dst_data_stream_0_V_din = grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_din.read();
}

void sobel_Sobel::thread_p_dst_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        p_dst_data_stream_0_V_write = grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_write.read();
    } else {
        p_dst_data_stream_0_V_write = ap_const_logic_0;
    }
}

void sobel_Sobel::thread_p_dst_data_stream_1_V_din() {
    p_dst_data_stream_1_V_din = grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_din.read();
}

void sobel_Sobel::thread_p_dst_data_stream_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        p_dst_data_stream_1_V_write = grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_write.read();
    } else {
        p_dst_data_stream_1_V_write = ap_const_logic_0;
    }
}

void sobel_Sobel::thread_p_dst_data_stream_2_V_din() {
    p_dst_data_stream_2_V_din = grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_din.read();
}

void sobel_Sobel::thread_p_dst_data_stream_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        p_dst_data_stream_2_V_write = grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_write.read();
    } else {
        p_dst_data_stream_2_V_write = ap_const_logic_0;
    }
}

void sobel_Sobel::thread_p_src_data_stream_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        p_src_data_stream_0_V_read = grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_read.read();
    } else {
        p_src_data_stream_0_V_read = ap_const_logic_0;
    }
}

void sobel_Sobel::thread_p_src_data_stream_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        p_src_data_stream_1_V_read = grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_read.read();
    } else {
        p_src_data_stream_1_V_read = ap_const_logic_0;
    }
}

void sobel_Sobel::thread_p_src_data_stream_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()))) {
        p_src_data_stream_2_V_read = grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_read.read();
    } else {
        p_src_data_stream_2_V_read = ap_const_logic_0;
    }
}

void sobel_Sobel::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!ap_sig_bdd_59.read()) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_sobel_Filter2D_fu_61_ap_done.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

