// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _sobel_Sobel_HH_
#define _sobel_Sobel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "sobel_Filter2D.h"

namespace ap_rtl {

struct sobel_Sobel : public sc_module {
    // Port declarations 27
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<12> > p_src_rows_V_read;
    sc_in< sc_lv<12> > p_src_cols_V_read;
    sc_in< sc_lv<8> > p_src_data_stream_0_V_dout;
    sc_in< sc_logic > p_src_data_stream_0_V_empty_n;
    sc_out< sc_logic > p_src_data_stream_0_V_read;
    sc_in< sc_lv<8> > p_src_data_stream_1_V_dout;
    sc_in< sc_logic > p_src_data_stream_1_V_empty_n;
    sc_out< sc_logic > p_src_data_stream_1_V_read;
    sc_in< sc_lv<8> > p_src_data_stream_2_V_dout;
    sc_in< sc_logic > p_src_data_stream_2_V_empty_n;
    sc_out< sc_logic > p_src_data_stream_2_V_read;
    sc_out< sc_lv<8> > p_dst_data_stream_0_V_din;
    sc_in< sc_logic > p_dst_data_stream_0_V_full_n;
    sc_out< sc_logic > p_dst_data_stream_0_V_write;
    sc_out< sc_lv<8> > p_dst_data_stream_1_V_din;
    sc_in< sc_logic > p_dst_data_stream_1_V_full_n;
    sc_out< sc_logic > p_dst_data_stream_1_V_write;
    sc_out< sc_lv<8> > p_dst_data_stream_2_V_din;
    sc_in< sc_logic > p_dst_data_stream_2_V_full_n;
    sc_out< sc_logic > p_dst_data_stream_2_V_write;


    // Module declarations
    sobel_Sobel(sc_module_name name);
    SC_HAS_PROCESS(sobel_Sobel);

    ~sobel_Sobel();

    sc_trace_file* mVcdFile;

    sobel_Filter2D* grp_sobel_Filter2D_fu_61;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_sig_cseq_ST_st1_fsm_0;
    sc_signal< bool > ap_sig_bdd_21;
    sc_signal< bool > ap_sig_bdd_59;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_ap_start;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_ap_done;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_ap_idle;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_ap_ready;
    sc_signal< sc_lv<12> > grp_sobel_Filter2D_fu_61_p_src_rows_V_read;
    sc_signal< sc_lv<12> > grp_sobel_Filter2D_fu_61_p_src_cols_V_read;
    sc_signal< sc_lv<8> > grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_dout;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_empty_n;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_read;
    sc_signal< sc_lv<8> > grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_dout;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_empty_n;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_read;
    sc_signal< sc_lv<8> > grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_dout;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_empty_n;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_read;
    sc_signal< sc_lv<8> > grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_din;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_full_n;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_write;
    sc_signal< sc_lv<8> > grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_din;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_full_n;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_write;
    sc_signal< sc_lv<8> > grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_din;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_full_n;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_write;
    sc_signal< sc_logic > grp_sobel_Filter2D_fu_61_ap_start_ap_start_reg;
    sc_signal< sc_logic > ap_sig_cseq_ST_st2_fsm_1;
    sc_signal< bool > ap_sig_bdd_97;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_st1_fsm_0;
    static const sc_lv<2> ap_ST_st2_fsm_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sig_bdd_21();
    void thread_ap_sig_bdd_59();
    void thread_ap_sig_bdd_97();
    void thread_ap_sig_cseq_ST_st1_fsm_0();
    void thread_ap_sig_cseq_ST_st2_fsm_1();
    void thread_grp_sobel_Filter2D_fu_61_ap_start();
    void thread_grp_sobel_Filter2D_fu_61_p_dst_data_stream_0_V_full_n();
    void thread_grp_sobel_Filter2D_fu_61_p_dst_data_stream_1_V_full_n();
    void thread_grp_sobel_Filter2D_fu_61_p_dst_data_stream_2_V_full_n();
    void thread_grp_sobel_Filter2D_fu_61_p_src_cols_V_read();
    void thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_dout();
    void thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_0_V_empty_n();
    void thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_dout();
    void thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_1_V_empty_n();
    void thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_dout();
    void thread_grp_sobel_Filter2D_fu_61_p_src_data_stream_2_V_empty_n();
    void thread_grp_sobel_Filter2D_fu_61_p_src_rows_V_read();
    void thread_p_dst_data_stream_0_V_din();
    void thread_p_dst_data_stream_0_V_write();
    void thread_p_dst_data_stream_1_V_din();
    void thread_p_dst_data_stream_1_V_write();
    void thread_p_dst_data_stream_2_V_din();
    void thread_p_dst_data_stream_2_V_write();
    void thread_p_src_data_stream_0_V_read();
    void thread_p_src_data_stream_1_V_read();
    void thread_p_src_data_stream_2_V_read();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
