// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#ifndef _sobel_borderInterpolate_HH_
#define _sobel_borderInterpolate_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct sobel_borderInterpolate : public sc_module {
    // Port declarations 6
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<12> > p;
    sc_in< sc_lv<12> > len;
    sc_out< sc_lv<14> > ap_return;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    sobel_borderInterpolate(sc_module_name name);
    SC_HAS_PROCESS(sobel_borderInterpolate);

    ~sobel_borderInterpolate();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<12> > len_read_reg_195;
    sc_signal< sc_lv<12> > p_read_reg_200;
    sc_signal< sc_lv<1> > or_cond_58_fu_63_p2;
    sc_signal< sc_lv<1> > or_cond_58_reg_205;
    sc_signal< sc_lv<1> > tmp_1_fu_69_p2;
    sc_signal< sc_lv<1> > tmp_1_reg_211;
    sc_signal< sc_lv<13> > p_p2_fu_89_p3;
    sc_signal< sc_lv<13> > p_p2_reg_217;
    sc_signal< sc_lv<1> > tmp_3_fu_97_p2;
    sc_signal< sc_lv<1> > tmp_3_reg_223;
    sc_signal< sc_lv<1> > sel_tmp1_fu_109_p2;
    sc_signal< sc_lv<1> > sel_tmp1_reg_228;
    sc_signal< sc_lv<1> > tmp_fu_39_p3;
    sc_signal< sc_lv<13> > p_cast1_fu_35_p1;
    sc_signal< sc_lv<13> > len_cast4_cast_fu_53_p1;
    sc_signal< sc_lv<1> > tmp_s_fu_57_p2;
    sc_signal< sc_lv<1> > rev_fu_47_p2;
    sc_signal< sc_lv<1> > tmp_63_fu_75_p3;
    sc_signal< sc_lv<13> > p_assign_fu_83_p2;
    sc_signal< sc_lv<1> > tmp_not_fu_103_p2;
    sc_signal< sc_lv<13> > tmp_4_fu_121_p3;
    sc_signal< sc_lv<14> > tmp_4_cast_cast_fu_128_p1;
    sc_signal< sc_lv<14> > tmp_5_fu_132_p2;
    sc_signal< sc_lv<14> > p_p2_cast_cast_fu_118_p1;
    sc_signal< sc_lv<1> > sel_tmp6_demorgan_fu_148_p2;
    sc_signal< sc_lv<1> > sel_tmp6_fu_152_p2;
    sc_signal< sc_lv<1> > sel_tmp7_fu_158_p2;
    sc_signal< sc_lv<13> > newSel_fu_163_p3;
    sc_signal< sc_lv<1> > sel_tmp2_fu_144_p2;
    sc_signal< sc_lv<14> > p_cast_cast_fu_115_p1;
    sc_signal< sc_lv<14> > p_assign_1_fu_138_p2;
    sc_signal< sc_lv<1> > or_cond_fu_174_p2;
    sc_signal< sc_lv<14> > newSel_cast_fu_170_p1;
    sc_signal< sc_lv<14> > newSel9_fu_180_p3;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<12> ap_const_lv12_1;
    static const sc_lv<13> ap_const_lv13_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<14> ap_const_lv14_3FFE;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_return();
    void thread_len_cast4_cast_fu_53_p1();
    void thread_newSel9_fu_180_p3();
    void thread_newSel_cast_fu_170_p1();
    void thread_newSel_fu_163_p3();
    void thread_or_cond_58_fu_63_p2();
    void thread_or_cond_fu_174_p2();
    void thread_p_assign_1_fu_138_p2();
    void thread_p_assign_fu_83_p2();
    void thread_p_cast1_fu_35_p1();
    void thread_p_cast_cast_fu_115_p1();
    void thread_p_p2_cast_cast_fu_118_p1();
    void thread_p_p2_fu_89_p3();
    void thread_rev_fu_47_p2();
    void thread_sel_tmp1_fu_109_p2();
    void thread_sel_tmp2_fu_144_p2();
    void thread_sel_tmp6_demorgan_fu_148_p2();
    void thread_sel_tmp6_fu_152_p2();
    void thread_sel_tmp7_fu_158_p2();
    void thread_tmp_1_fu_69_p2();
    void thread_tmp_3_fu_97_p2();
    void thread_tmp_4_cast_cast_fu_128_p1();
    void thread_tmp_4_fu_121_p3();
    void thread_tmp_5_fu_132_p2();
    void thread_tmp_63_fu_75_p3();
    void thread_tmp_fu_39_p3();
    void thread_tmp_not_fu_103_p2();
    void thread_tmp_s_fu_57_p2();
};

}

using namespace ap_rtl;

#endif
