set_property SRC_FILE_INFO {cfile:d:/Users/Manu/Desktop/VersionesProyecto/Proyecto_v3_0/Proyecto_v3_0.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc rfile:../../../Proyecto_v3_0.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc id:1 order:EARLY scoped_inst:system_i/processing_system7_0/inst} [current_design]
set_property SRC_FILE_INFO {cfile:D:/Users/Manu/Desktop/VersionesProyecto/Proyecto_v3_0/Proyecto_v3_0.srcs/constrs_1/imports/Proyecto/ZYBO_Master.xdc rfile:../../../Proyecto_v3_0.srcs/constrs_1/imports/Proyecto/ZYBO_Master.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Users/Manu/Desktop/VersionesProyecto/Proyecto_v3_0/Proyecto_v3_0.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc rfile:../../../Proyecto_v3_0.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc id:3 order:LATE scoped_inst:system_i/axi_vdma_VGA/U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Users/Manu/Desktop/VersionesProyecto/Proyecto_v3_0/Proyecto_v3_0.srcs/sources_1/bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1_clocks.xdc rfile:../../../Proyecto_v3_0.srcs/sources_1/bd/system/ip/system_axi_vdma_1_1/system_axi_vdma_1_1_clocks.xdc id:4 order:LATE scoped_inst:system_i/axi_vdma_HDMI/U0} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Users/Manu/Desktop/VersionesProyecto/Proyecto_v3_0/Proyecto_v3_0.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_clocks.xdc rfile:../../../Proyecto_v3_0.srcs/sources_1/bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0_clocks.xdc id:5 order:LATE scoped_inst:system_i/HDMI_VideoIN_axi4s/inst} [current_design]
set_property SRC_FILE_INFO {cfile:d:/Users/Manu/Desktop/VersionesProyecto/Proyecto_v3_0/Proyecto_v3_0.srcs/sources_1/bd/system/ip/system_axi_vdma_HDMI_0/system_axi_vdma_HDMI_0_clocks.xdc rfile:../../../Proyecto_v3_0.srcs/sources_1/bd/system/ip/system_axi_vdma_HDMI_0/system_axi_vdma_HDMI_0_clocks.xdc id:6 order:LATE scoped_inst:system_i/axi_vdma_HLS/U0} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_2 0.15
set_property src_info {type:SCOPED_XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_0 0.3
set_property src_info {type:SCOPED_XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter clk_fpga_1 0.19998
set_property src_info {type:XDC file:2 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC MMCME2_ADV_X0Y0 [get_cells system_i/axi_dispctrl_0/inst/DONT_USE_BUFR_DIV5.Inst_mmcme2_drp/mmcm_adv_inst]
set_property src_info {type:XDC file:2 line:178 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name vga_pxlclk -source [get_pins {system_i/processing_system7_0/inst/PS7_i/FCLKCLK[0]}] -multiply_by 1 [get_pins system_i/axi_dispctrl_0/inst/DONT_USE_BUFR_DIV5.BUFG_inst/O]
set_property src_info {type:XDC file:2 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks vga_pxlclk] -to [get_clocks clk_fpga_0]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks vga_pxlclk]
set_property src_info {type:XDC file:2 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports {JE[0]}]
set_property src_info {type:XDC file:2 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {JE[0]}]
set_property src_info {type:XDC file:2 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {JE[1]}]
set_property src_info {type:XDC file:2 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {JE[1]}]
set_property src_info {type:XDC file:2 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J15 [get_ports {JE[2]}]
set_property src_info {type:XDC file:2 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {JE[2]}]
set_property src_info {type:XDC file:2 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H15 [get_ports {JE[3]}]
set_property src_info {type:XDC file:2 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {JE[3]}]
set_property src_info {type:XDC file:2 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V13 [get_ports {JE[4]}]
set_property src_info {type:XDC file:2 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {JE[4]}]
set_property src_info {type:XDC file:2 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U17 [get_ports {JE[5]}]
set_property src_info {type:XDC file:2 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {JE[5]}]
set_property src_info {type:XDC file:2 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T17 [get_ports {JE[6]}]
set_property src_info {type:XDC file:2 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {JE[6]}]
set_property src_info {type:XDC file:2 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y17 [get_ports {JE[7]}]
set_property src_info {type:XDC file:2 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {JE[7]}]
set_property src_info {type:XDC file:2 line:427 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_2_0/clk [get_nets [list {JE_OBUF[7]}]]
set_property src_info {type:XDC file:2 line:428 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_PXL_CLK_O]
set_property src_info {type:SCOPED_XDC file:3 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*MM2S_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*MM2S_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins system_i/axi_vdma_VGA/U0/m_axis_mm2s_aclk]]]
set_property src_info {type:SCOPED_XDC file:3 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*MM2S_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*MM2S_LINEBUFFER*/fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins system_i/axi_vdma_VGA/U0/m_axi_mm2s_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*S2MM_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*S2MM_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins system_i/axi_vdma_HDMI/U0/m_axi_s2mm_aclk]]]
set_property src_info {type:SCOPED_XDC file:4 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*S2MM_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*S2MM_LINEBUFFER*/fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins system_i/axi_vdma_HDMI/U0/s_axis_s2mm_aclk]]]
set_property src_info {type:SCOPED_XDC file:5 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins system_i/HDMI_VideoIN_axi4s/inst/vid_io_in_clk]] -to [all_registers -clock [get_clocks -of_objects [get_pins system_i/HDMI_VideoIN_axi4s/inst/aclk]]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins system_i/HDMI_VideoIN_axi4s/inst/vid_io_in_clk]]]
set_property src_info {type:SCOPED_XDC file:5 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_clocks -of_objects [get_pins system_i/HDMI_VideoIN_axi4s/inst/aclk]] -to [all_registers -clock [get_clocks -of_objects [get_pins system_i/HDMI_VideoIN_axi4s/inst/vid_io_in_clk]]] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins system_i/HDMI_VideoIN_axi4s/inst/aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*MM2S_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*MM2S_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins system_i/axi_vdma_HLS/U0/m_axis_mm2s_aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*MM2S_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*MM2S_LINEBUFFER*/fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins system_i/axi_vdma_HLS/U0/m_axi_mm2s_aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*S2MM_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/rd_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*S2MM_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].wr_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins system_i/axi_vdma_HLS/U0/m_axi_s2mm_aclk]]]
set_property src_info {type:SCOPED_XDC file:6 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -from [get_cells -hierarchical -filter {NAME =~*S2MM_LINEBUFFER*fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/wr_pntr_gc_reg[*]}] -to [get_cells -hierarchical -filter {NAME =~*S2MM_LINEBUFFER*/fg_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/gntv_or_sync_fifo.gcx.clkx/gsync_stage[*].rd_stg_inst/Q_reg_reg[*]}] -datapath_only [get_property -min PERIOD [get_clocks -of_objects [get_pins system_i/axi_vdma_HLS/U0/s_axis_s2mm_aclk]]]
