// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.4
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sobel_Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_rows_V_read,
        p_src_cols_V_read,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write,
        p_kernel_val_0_V_1_read,
        p_kernel_val_0_V_2_read,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_2_read,
        p_kernel_val_2_V_0_read,
        p_kernel_val_2_V_1_read
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 5'b1;
parameter    ap_ST_st2_fsm_1 = 5'b10;
parameter    ap_ST_st3_fsm_2 = 5'b100;
parameter    ap_ST_pp0_stg0_fsm_3 = 5'b1000;
parameter    ap_ST_st12_fsm_4 = 5'b10000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv11_0 = 11'b00000000000;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv10_5 = 10'b101;
parameter    ap_const_lv11_2 = 11'b10;
parameter    ap_const_lv11_7FD = 11'b11111111101;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv10_3FF = 10'b1111111111;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv13_1FFE = 13'b1111111111110;
parameter    ap_const_lv11_1 = 11'b1;
parameter    ap_const_lv13_2 = 13'b10;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv10_4 = 10'b100;
parameter    ap_const_lv11_7FC = 11'b11111111100;
parameter    ap_const_lv11_7FF = 11'b11111111111;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv10_2 = 10'b10;
parameter    ap_const_lv11_7FB = 11'b11111111011;
parameter    ap_const_lv11_5 = 11'b101;
parameter    ap_const_lv11_7FA = 11'b11111111010;
parameter    ap_const_lv11_6 = 11'b110;
parameter    ap_const_lv12_FFF = 12'b111111111111;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv9_0 = 9'b000000000;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] p_src_rows_V_read;
input  [11:0] p_src_cols_V_read;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;
input  [2:0] p_kernel_val_0_V_1_read;
input  [1:0] p_kernel_val_0_V_2_read;
input  [1:0] p_kernel_val_1_V_0_read;
input  [2:0] p_kernel_val_1_V_2_read;
input  [1:0] p_kernel_val_2_V_0_read;
input  [3:0] p_kernel_val_2_V_1_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm = 5'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_23;
reg   [10:0] p_025_0_i_reg_355;
wire   [9:0] heightloop_fu_427_p2;
reg   [9:0] heightloop_reg_1740;
wire   [10:0] widthloop_fu_433_p2;
reg   [10:0] widthloop_reg_1745;
wire   [11:0] tmp_27_cast_fu_445_p1;
reg   [11:0] tmp_27_cast_reg_1750;
wire   [1:0] p_neg228_i_cast_fu_453_p2;
reg   [1:0] p_neg228_i_cast_reg_1755;
wire   [9:0] ref_fu_459_p2;
reg   [9:0] ref_reg_1761;
wire   [10:0] ref_cast_fu_465_p1;
reg   [10:0] ref_cast_reg_1766;
wire   [11:0] len_cast4_i_cast_fu_469_p1;
reg   [11:0] len_cast4_i_cast_reg_1771;
wire  signed [14:0] tmp_5_cast_i_fu_489_p1;
reg  signed [14:0] tmp_5_cast_i_reg_1777;
wire  signed [10:0] OP2_V_0_1_cast_fu_493_p1;
reg  signed [10:0] OP2_V_0_1_cast_reg_1782;
wire  signed [9:0] OP2_V_0_2_cast_fu_497_p1;
reg  signed [9:0] OP2_V_0_2_cast_reg_1787;
wire  signed [9:0] OP2_V_1_cast_fu_501_p1;
reg  signed [9:0] OP2_V_1_cast_reg_1792;
wire  signed [10:0] OP2_V_1_2_cast_fu_505_p1;
reg  signed [10:0] OP2_V_1_2_cast_reg_1797;
wire  signed [9:0] OP2_V_2_cast_fu_509_p1;
reg  signed [9:0] OP2_V_2_cast_reg_1802;
wire  signed [11:0] OP2_V_2_1_cast_fu_513_p1;
reg  signed [11:0] OP2_V_2_1_cast_reg_1807;
wire   [10:0] tmp_17_fu_517_p1;
reg   [10:0] tmp_17_reg_1812;
wire   [0:0] tmp_1_i1_fu_521_p2;
reg   [0:0] tmp_1_i1_reg_1819;
wire   [11:0] len_cast_i1_fu_527_p1;
reg   [11:0] len_cast_i1_reg_1828;
wire   [12:0] tmp_5_i1_fu_541_p2;
reg   [12:0] tmp_5_i1_reg_1834;
wire   [1:0] tmp_5_i2_fu_559_p2;
reg   [1:0] tmp_5_i2_reg_1839;
wire   [9:0] i_V_fu_574_p2;
reg   [9:0] i_V_reg_1848;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_96;
wire   [0:0] tmp_3_fu_580_p2;
reg   [0:0] tmp_3_reg_1853;
wire   [0:0] tmp_2_fu_569_p2;
reg   [0:0] tmp_25_reg_1858;
wire   [0:0] tmp_i1_fu_640_p2;
reg   [0:0] tmp_i1_reg_1862;
wire   [1:0] tmp_26_fu_654_p1;
reg   [1:0] tmp_26_reg_1867;
wire   [1:0] tmp_30_fu_666_p3;
reg   [1:0] tmp_30_reg_1873;
wire   [1:0] tmp_36_fu_735_p1;
reg   [1:0] tmp_36_reg_1878;
wire   [0:0] tmp_3_i2_fu_739_p2;
reg   [0:0] tmp_3_i2_reg_1883;
wire   [1:0] sel_tmp_i2_fu_749_p3;
reg   [1:0] sel_tmp_i2_reg_1888;
wire   [0:0] sel_tmp1_i2_fu_763_p2;
reg   [0:0] sel_tmp1_i2_reg_1893;
wire   [0:0] sel_tmp6_demorgan_i2_fu_769_p2;
reg   [0:0] sel_tmp6_demorgan_i2_reg_1898;
wire   [1:0] tmp_37_fu_774_p1;
reg   [1:0] tmp_37_reg_1903;
wire   [1:0] tmp_41_fu_839_p1;
reg   [1:0] tmp_41_reg_1910;
wire   [0:0] tmp_3_i3_fu_843_p2;
reg   [0:0] tmp_3_i3_reg_1915;
wire   [0:0] sel_tmp1_i3_fu_859_p2;
reg   [0:0] sel_tmp1_i3_reg_1920;
wire   [0:0] sel_tmp6_demorgan_i3_fu_865_p2;
reg   [0:0] sel_tmp6_demorgan_i3_reg_1925;
wire   [1:0] newSel1_fu_870_p3;
reg   [1:0] newSel1_reg_1930;
wire   [0:0] brmerge_fu_878_p2;
reg   [0:0] brmerge_reg_1935;
wire   [0:0] sel_tmp8_fu_906_p2;
reg   [0:0] sel_tmp8_reg_1939;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_144;
wire   [0:0] sel_tmp1_fu_911_p2;
reg   [0:0] sel_tmp1_reg_1944;
wire   [0:0] sel_tmp3_fu_950_p2;
reg   [0:0] sel_tmp3_reg_1949;
wire   [0:0] sel_tmp5_fu_955_p2;
reg   [0:0] sel_tmp5_reg_1954;
wire   [1:0] locy_2_t_fu_995_p2;
reg   [1:0] locy_2_t_reg_1959;
wire   [0:0] tmp_1_fu_1004_p2;
reg   [0:0] tmp_1_reg_1963;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_3;
reg    ap_sig_bdd_161;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg   [0:0] ap_reg_ppstg_tmp_1_reg_1963_pp0_it1;
reg   [0:0] or_cond7_reg_2004;
reg   [0:0] ap_reg_ppstg_or_cond7_reg_2004_pp0_it1;
reg    ap_sig_bdd_180;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg   [0:0] or_cond221_i_reg_1972;
reg   [0:0] ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it6;
reg    ap_sig_bdd_198;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg   [0:0] ap_reg_ppstg_tmp_1_reg_1963_pp0_it2;
reg   [0:0] ap_reg_ppstg_tmp_1_reg_1963_pp0_it3;
wire   [10:0] j_V_fu_1009_p2;
wire   [0:0] or_cond221_i_fu_1031_p2;
reg   [0:0] ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it1;
reg   [0:0] ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it2;
reg   [0:0] ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it3;
reg   [0:0] ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it4;
reg   [0:0] ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it5;
wire   [0:0] tmp_45_fu_1075_p3;
reg   [0:0] tmp_45_reg_1976;
reg   [0:0] ap_reg_ppstg_tmp_45_reg_1976_pp0_it1;
wire   [14:0] p_p2_cast1_i_cast_fu_1101_p1;
reg   [14:0] p_p2_cast1_i_cast_reg_1980;
wire   [0:0] tmp_3_i_fu_1105_p2;
reg   [0:0] tmp_3_i_reg_1985;
wire   [14:0] sel_tmp_i_fu_1115_p3;
reg   [14:0] sel_tmp_i_reg_1990;
wire   [0:0] sel_tmp6_i_fu_1129_p2;
reg   [0:0] sel_tmp6_i_reg_1995;
wire   [0:0] tmp_9_fu_1141_p2;
reg   [0:0] tmp_9_reg_2000;
reg   [0:0] ap_reg_ppstg_tmp_9_reg_2000_pp0_it1;
wire   [0:0] or_cond7_fu_1146_p2;
wire   [0:0] tmp_10_fu_1152_p2;
reg   [0:0] tmp_10_reg_2008;
reg   [0:0] ap_reg_ppstg_tmp_10_reg_2008_pp0_it1;
wire   [1:0] col_assign_fu_1157_p2;
reg   [1:0] col_assign_reg_2012;
reg   [1:0] ap_reg_ppstg_col_assign_reg_2012_pp0_it1;
reg   [10:0] k_buf_0_val_0_addr_reg_2018;
reg   [10:0] k_buf_0_val_1_addr_reg_2024;
reg   [10:0] k_buf_0_val_2_addr_reg_2030;
wire   [1:0] col_assign_2_fu_1187_p2;
reg   [1:0] col_assign_2_reg_2036;
reg   [7:0] src_kernel_win_0_val_0_1_6_reg_2042;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_2042_pp0_it3;
reg   [7:0] src_kernel_win_0_val_2_1_9_reg_2048;
reg   [7:0] src_kernel_win_0_val_1_1_6_reg_2054;
reg   [7:0] src_kernel_win_0_val_0_1_lo_reg_2059;
reg   [7:0] ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_2059_pp0_it4;
reg   [7:0] src_kernel_win_0_val_1_1_lo_reg_2064;
wire   [8:0] p_Val2_s_fu_1425_p2;
reg   [8:0] p_Val2_s_reg_2069;
wire  signed [10:0] p_Val2_0_1_fu_1434_p2;
reg  signed [10:0] p_Val2_0_1_reg_2074;
wire  signed [9:0] p_Val2_0_2_fu_1443_p2;
reg  signed [9:0] p_Val2_0_2_reg_2079;
wire  signed [9:0] p_Val2_1_fu_1452_p2;
reg  signed [9:0] p_Val2_1_reg_2084;
wire  signed [12:0] p_Val2_5_1_1_fu_1496_p2;
reg  signed [12:0] p_Val2_5_1_1_reg_2089;
wire  signed [10:0] p_Val2_1_2_fu_1505_p2;
reg  signed [10:0] p_Val2_1_2_reg_2094;
wire  signed [9:0] p_Val2_2_fu_1514_p2;
reg  signed [9:0] p_Val2_2_reg_2099;
wire  signed [11:0] p_Val2_2_1_fu_1522_p2;
reg  signed [11:0] p_Val2_2_1_reg_2104;
reg   [0:0] isneg_reg_2109;
wire   [7:0] p_Val2_4_fu_1578_p1;
reg   [7:0] p_Val2_4_reg_2115;
reg   [5:0] tmp_15_reg_2120;
wire   [7:0] p_Val2_6_fu_1621_p3;
reg   [7:0] p_Val2_6_reg_2125;
wire   [10:0] k_buf_0_val_0_address0;
reg    k_buf_0_val_0_ce0;
wire   [7:0] k_buf_0_val_0_q0;
wire   [10:0] k_buf_0_val_0_address1;
reg    k_buf_0_val_0_ce1;
reg    k_buf_0_val_0_we1;
wire   [7:0] k_buf_0_val_0_d1;
wire   [10:0] k_buf_0_val_1_address0;
reg    k_buf_0_val_1_ce0;
wire   [7:0] k_buf_0_val_1_q0;
wire   [10:0] k_buf_0_val_1_address1;
reg    k_buf_0_val_1_ce1;
reg    k_buf_0_val_1_we1;
wire   [7:0] k_buf_0_val_1_d1;
wire   [10:0] k_buf_0_val_2_address0;
reg    k_buf_0_val_2_ce0;
wire   [7:0] k_buf_0_val_2_q0;
wire   [10:0] k_buf_0_val_2_address1;
reg    k_buf_0_val_2_ce1;
reg    k_buf_0_val_2_we1;
wire   [7:0] k_buf_0_val_2_d1;
reg   [9:0] p_012_0_i_reg_344;
reg    ap_sig_cseq_ST_st12_fsm_4;
reg    ap_sig_bdd_375;
wire   [63:0] tmp_7_fu_1180_p1;
reg   [7:0] src_kernel_win_0_val_0_1_fu_162;
wire   [7:0] src_kernel_win_0_val_0_0_fu_1213_p3;
wire   [7:0] col_buf_0_val_0_0_9_fu_1273_p3;
reg   [7:0] src_kernel_win_0_val_0_2_fu_166;
reg   [7:0] col_buf_0_val_0_0_3_fu_170;
reg   [7:0] src_kernel_win_0_val_2_1_fu_174;
reg   [7:0] src_kernel_win_0_val_1_1_fu_178;
wire   [7:0] src_kernel_win_0_val_1_0_fu_1228_p3;
wire   [7:0] right_border_buf_0_val_1_2_11_fu_1290_p3;
reg   [7:0] src_kernel_win_0_val_1_2_fu_182;
reg   [7:0] col_buf_0_val_0_0_5_fu_186;
reg   [7:0] src_kernel_win_0_val_2_2_fu_190;
reg   [7:0] col_buf_0_val_0_0_6_fu_194;
reg   [7:0] right_border_buf_0_val_1_2_1_fu_198;
wire   [7:0] right_border_buf_0_val_1_2_8_fu_1382_p3;
reg   [7:0] right_border_buf_0_val_1_2_2_fu_202;
wire   [7:0] right_border_buf_0_val_1_2_6_fu_1373_p3;
reg   [7:0] right_border_buf_0_val_1_2_7_fu_206;
wire   [7:0] right_border_buf_0_val_1_2_4_fu_1356_p3;
reg   [7:0] right_border_buf_0_val_0_0_fu_222;
reg   [7:0] right_border_buf_0_val_0_1_fu_226;
reg   [7:0] right_border_buf_0_val_0_2_fu_230;
wire   [9:0] tmp_11_fu_419_p1;
wire   [10:0] tmp_12_fu_423_p1;
wire   [10:0] tmp_s_fu_439_p2;
wire   [1:0] tmp_13_fu_449_p1;
wire   [11:0] tmp_14_fu_473_p2;
wire   [12:0] tmp_4_cast_i_cast_fu_479_p1;
wire   [12:0] tmp_5_i_fu_483_p2;
wire   [11:0] tmp_18_fu_531_p2;
wire   [12:0] tmp_4_cast_i42_cast_fu_537_p1;
wire   [0:0] tmp_19_fu_547_p1;
wire   [1:0] tmp_4_i2_fu_551_p3;
wire   [10:0] tmp_28_cast7_fu_565_p1;
wire   [10:0] ImagLoc_y_fu_586_p2;
wire   [9:0] tmp_24_fu_598_p4;
wire   [0:0] icmp_fu_608_p2;
wire   [0:0] tmp_6_fu_614_p2;
wire   [12:0] p_cast_i32_cast_fu_645_p1;
wire   [9:0] p_i_fu_633_p3;
wire   [12:0] p_assign_2_fu_649_p2;
wire   [1:0] tmp_28_fu_658_p1;
wire   [1:0] tmp_29_fu_662_p1;
wire   [10:0] y_1_fu_674_p2;
wire   [0:0] tmp_33_fu_680_p3;
wire  signed [11:0] p_cast8_i57_cast_fu_694_p1;
wire   [0:0] tmp_i2_fu_698_p2;
wire   [0:0] rev_fu_688_p2;
wire   [0:0] tmp_35_fu_713_p3;
wire   [10:0] p_assign_3_fu_721_p2;
wire   [10:0] p_p2_i1_fu_727_p3;
wire   [0:0] or_cond_i2_fu_703_p2;
wire   [1:0] tmp_34_fu_709_p1;
wire   [1:0] p_assign_1_cast_i_fu_744_p2;
wire   [0:0] tmp_i2_not_fu_757_p2;
wire   [10:0] y_1_1_fu_778_p2;
wire   [0:0] tmp_38_fu_784_p3;
wire  signed [11:0] p_cast8_i88_cast_fu_798_p1;
wire   [0:0] tmp_i3_fu_802_p2;
wire   [0:0] rev1_fu_792_p2;
wire   [0:0] tmp_40_fu_817_p3;
wire   [10:0] p_assign_4_fu_825_p2;
wire   [10:0] p_p2_i2_fu_831_p3;
wire   [0:0] tmp_i3_not_fu_853_p2;
wire   [0:0] or_cond_i3_fu_807_p2;
wire   [1:0] tmp_39_fu_813_p1;
wire   [1:0] p_assign_1_cast_i1_fu_848_p2;
wire   [0:0] tmp_4_fu_592_p2;
wire   [0:0] or_cond6_fu_619_p2;
wire   [0:0] sel_tmp1_i1_fu_884_p2;
wire   [0:0] sel_tmp2_i1_fu_889_p2;
wire   [1:0] tmp_31_fu_894_p3;
wire   [1:0] tmp_32_fu_901_p2;
wire   [0:0] sel_tmp2_i2_fu_917_p2;
wire   [0:0] sel_tmp6_i2_fu_928_p2;
wire   [0:0] sel_tmp7_i2_fu_933_p2;
wire   [1:0] sel_tmp3_i2_fu_921_p3;
wire   [1:0] p_assign_2_i2_fu_938_p3;
wire   [1:0] locy_1_t_fu_945_p2;
wire   [0:0] sel_tmp6_i3_fu_965_p2;
wire   [0:0] sel_tmp7_i3_fu_970_p2;
wire   [0:0] sel_tmp2_i3_fu_961_p2;
wire   [0:0] or_cond_fu_982_p2;
wire   [1:0] newSel_fu_975_p3;
wire   [1:0] newSel2_fu_988_p3;
wire   [9:0] tmp_42_fu_1015_p4;
wire   [0:0] icmp1_fu_1025_p2;
wire   [11:0] tmp_31_cast6_fu_1000_p1;
wire   [11:0] ImagLoc_x_fu_1036_p2;
wire   [0:0] tmp_44_fu_1046_p3;
wire   [0:0] tmp_i_fu_1060_p2;
wire   [0:0] rev2_fu_1054_p2;
wire   [11:0] p_assign_fu_1083_p2;
wire   [11:0] p_p2_i_fu_1089_p3;
wire  signed [13:0] p_p2_i_cast_fu_1097_p1;
wire   [0:0] or_cond_i1_fu_1065_p2;
wire  signed [14:0] p_cast_i_cast_fu_1071_p1;
wire  signed [14:0] p_assign_1_fu_1110_p2;
wire   [0:0] tmp_i_not_fu_1123_p2;
wire   [0:0] tmp_8_fu_1135_p2;
wire   [1:0] tmp_43_fu_1042_p1;
wire   [0:0] sel_tmp7_i_fu_1162_p2;
wire   [14:0] p_assign_2_i_fu_1166_p3;
wire  signed [31:0] x_fu_1172_p1;
wire   [1:0] tmp_46_fu_1176_p1;
wire   [7:0] sel_tmp9_fu_1206_p3;
wire   [7:0] sel_tmp4_fu_1221_p3;
wire   [0:0] sel_tmp_fu_1255_p2;
wire   [0:0] sel_tmp2_fu_1268_p2;
wire   [7:0] col_buf_0_val_0_0_2_fu_1260_p3;
wire   [7:0] right_border_buf_0_val_1_2_fu_1282_p3;
wire   [0:0] sel_tmp6_fu_1338_p2;
wire   [0:0] sel_tmp7_fu_1351_p2;
wire   [7:0] right_border_buf_0_val_1_2_3_fu_1343_p3;
wire   [7:0] right_border_buf_0_val_1_2_5_fu_1365_p3;
wire   [8:0] OP1_V_0_cast_fu_1421_p1;
wire   [7:0] p_Val2_0_1_fu_1434_p0;
wire  signed [2:0] p_Val2_0_1_fu_1434_p1;
wire   [7:0] p_Val2_0_2_fu_1443_p0;
wire  signed [1:0] p_Val2_0_2_fu_1443_p1;
wire   [7:0] p_Val2_1_fu_1452_p0;
wire  signed [1:0] p_Val2_1_fu_1452_p1;
wire  signed [11:0] tmp_160_0_1_cast_fu_1471_p1;
wire  signed [11:0] tmp_160_0_cast_fu_1468_p1;
wire  signed [11:0] p_Val2_5_0_1_fu_1474_p2;
wire  signed [11:0] tmp_160_0_2_cast_cast_fu_1480_p1;
wire  signed [11:0] p_Val2_5_0_2_fu_1483_p2;
wire  signed [12:0] p_Val2_5_0_2_cast_fu_1489_p1;
wire  signed [12:0] tmp_160_1_cast_cast_fu_1493_p1;
wire   [7:0] p_Val2_1_2_fu_1505_p0;
wire  signed [2:0] p_Val2_1_2_fu_1505_p1;
wire   [7:0] p_Val2_2_fu_1514_p0;
wire  signed [1:0] p_Val2_2_fu_1514_p1;
wire   [7:0] p_Val2_2_1_fu_1522_p0;
wire  signed [3:0] p_Val2_2_1_fu_1522_p1;
wire  signed [12:0] tmp_160_1_2_cast_cast_fu_1531_p1;
wire  signed [12:0] p_Val2_5_1_2_fu_1534_p2;
wire  signed [12:0] p_Val2_2_cast_cast_fu_1539_p1;
wire  signed [12:0] p_Val2_5_2_fu_1542_p2;
wire  signed [13:0] p_Val2_5_2_cast_cast_fu_1548_p1;
wire  signed [13:0] tmp_160_2_1_cast_cast_fu_1552_p1;
wire  signed [13:0] p_Val2_5_2_1_fu_1555_p2;
wire   [13:0] tmp_160_2_2_cast_cast_fu_1561_p1;
wire  signed [13:0] p_Val2_3_fu_1564_p2;
wire   [0:0] not_i_i_i_fu_1597_p2;
wire   [0:0] tmp_i_i_fu_1592_p2;
wire   [0:0] overflow_fu_1602_p2;
wire   [0:0] tmp_i_i_42_fu_1616_p2;
wire   [7:0] p_mux_i_i_cast_fu_1608_p3;
reg   [4:0] ap_NS_fsm;
wire   [10:0] p_Val2_0_1_fu_1434_p00;
wire   [9:0] p_Val2_0_2_fu_1443_p00;
wire   [10:0] p_Val2_1_2_fu_1505_p00;
wire   [9:0] p_Val2_1_fu_1452_p00;
wire   [11:0] p_Val2_2_1_fu_1522_p00;
wire   [9:0] p_Val2_2_fu_1514_p00;


sobel_Filter2D_k_buf_0_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_0_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_0_address0 ),
    .ce0( k_buf_0_val_0_ce0 ),
    .q0( k_buf_0_val_0_q0 ),
    .address1( k_buf_0_val_0_address1 ),
    .ce1( k_buf_0_val_0_ce1 ),
    .we1( k_buf_0_val_0_we1 ),
    .d1( k_buf_0_val_0_d1 )
);

sobel_Filter2D_k_buf_0_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_1_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_1_address0 ),
    .ce0( k_buf_0_val_1_ce0 ),
    .q0( k_buf_0_val_1_q0 ),
    .address1( k_buf_0_val_1_address1 ),
    .ce1( k_buf_0_val_1_ce1 ),
    .we1( k_buf_0_val_1_we1 ),
    .d1( k_buf_0_val_1_d1 )
);

sobel_Filter2D_k_buf_0_val_0 #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
k_buf_0_val_2_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( k_buf_0_val_2_address0 ),
    .ce0( k_buf_0_val_2_ce0 ),
    .q0( k_buf_0_val_2_q0 ),
    .address1( k_buf_0_val_2_address1 ),
    .ce1( k_buf_0_val_2_ce1 ),
    .we1( k_buf_0_val_2_we1 ),
    .d1( k_buf_0_val_2_d1 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// ap_reg_ppiten_pp0_it0 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_1_fu_1004_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

/// ap_reg_ppiten_pp0_it1 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

/// ap_reg_ppiten_pp0_it2 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

/// ap_reg_ppiten_pp0_it3 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            if (~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) begin
                ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
            end else if ((ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) begin
                ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
            end
        end
    end
end

/// ap_reg_ppiten_pp0_it4 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

/// ap_reg_ppiten_pp0_it5 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

/// ap_reg_ppiten_pp0_it6 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

/// ap_reg_ppiten_pp0_it7 assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
            ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_4)) begin
        p_012_0_i_reg_344 <= i_V_reg_1848;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        p_012_0_i_reg_344 <= ap_const_lv10_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_1_fu_1004_p2))) begin
        p_025_0_i_reg_355 <= j_V_fu_1009_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        p_025_0_i_reg_355 <= ap_const_lv11_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1)))) begin
        src_kernel_win_0_val_0_1_fu_162 <= k_buf_0_val_0_q0;
    end else if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_9_reg_2000_pp0_it1) & (col_assign_2_reg_2036 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_9_reg_2000_pp0_it1) & (col_assign_2_reg_2036 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_9_reg_2000_pp0_it1) & ~(col_assign_2_reg_2036 == ap_const_lv2_1) & ~(col_assign_2_reg_2036 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_0_1_fu_162 <= col_buf_0_val_0_0_9_fu_1273_p3;
    end else if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_25_reg_1858) & (locy_2_t_reg_1959 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_25_reg_1858) & (locy_2_t_reg_1959 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_25_reg_1858) & ~(locy_2_t_reg_1959 == ap_const_lv2_1) & ~(locy_2_t_reg_1959 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_0_1_fu_162 <= src_kernel_win_0_val_0_0_fu_1213_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1)))) begin
        src_kernel_win_0_val_1_1_fu_178 <= k_buf_0_val_1_q0;
    end else if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_9_reg_2000_pp0_it1) & (col_assign_2_reg_2036 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_9_reg_2000_pp0_it1) & (col_assign_2_reg_2036 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_9_reg_2000_pp0_it1) & ~(col_assign_2_reg_2036 == ap_const_lv2_1) & ~(col_assign_2_reg_2036 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_1_1_fu_178 <= right_border_buf_0_val_1_2_11_fu_1290_p3;
    end else if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_25_reg_1858) & (locy_2_t_reg_1959 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_25_reg_1858) & (locy_2_t_reg_1959 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_25_reg_1858) & ~(locy_2_t_reg_1959 == ap_const_lv2_1) & ~(locy_2_t_reg_1959 == ap_const_lv2_0)))) begin
        src_kernel_win_0_val_1_1_fu_178 <= src_kernel_win_0_val_1_0_fu_1228_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_9_reg_2000_pp0_it1) & ~(col_assign_2_reg_2036 == ap_const_lv2_1) & ~(col_assign_2_reg_2036 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_174 <= right_border_buf_0_val_0_2_fu_230;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_9_reg_2000_pp0_it1) & (col_assign_2_reg_2036 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_174 <= right_border_buf_0_val_0_0_fu_222;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_9_reg_2000_pp0_it1) & (col_assign_2_reg_2036 == ap_const_lv2_1))) begin
        src_kernel_win_0_val_2_1_fu_174 <= right_border_buf_0_val_0_1_fu_226;
    end else if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_25_reg_1858) & ~(locy_2_t_reg_1959 == ap_const_lv2_1) & ~(locy_2_t_reg_1959 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_45_reg_1976_pp0_it1)))) begin
        src_kernel_win_0_val_2_1_fu_174 <= k_buf_0_val_2_q0;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_25_reg_1858) & (locy_2_t_reg_1959 == ap_const_lv2_0))) begin
        src_kernel_win_0_val_2_1_fu_174 <= k_buf_0_val_0_q0;
    end else if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & (ap_const_lv1_0 == brmerge_reg_1935) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == tmp_25_reg_1858) & (locy_2_t_reg_1959 == ap_const_lv2_1))) begin
        src_kernel_win_0_val_2_1_fu_174 <= k_buf_0_val_1_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        OP2_V_0_1_cast_reg_1782 <= OP2_V_0_1_cast_fu_493_p1;
        OP2_V_0_2_cast_reg_1787 <= OP2_V_0_2_cast_fu_497_p1;
        OP2_V_1_2_cast_reg_1797 <= OP2_V_1_2_cast_fu_505_p1;
        OP2_V_1_cast_reg_1792 <= OP2_V_1_cast_fu_501_p1;
        OP2_V_2_1_cast_reg_1807 <= OP2_V_2_1_cast_fu_513_p1;
        OP2_V_2_cast_reg_1802 <= OP2_V_2_cast_fu_509_p1;
        heightloop_reg_1740 <= heightloop_fu_427_p2;
        len_cast4_i_cast_reg_1771[0] <= len_cast4_i_cast_fu_469_p1[0];
len_cast4_i_cast_reg_1771[1] <= len_cast4_i_cast_fu_469_p1[1];
len_cast4_i_cast_reg_1771[2] <= len_cast4_i_cast_fu_469_p1[2];
len_cast4_i_cast_reg_1771[3] <= len_cast4_i_cast_fu_469_p1[3];
len_cast4_i_cast_reg_1771[4] <= len_cast4_i_cast_fu_469_p1[4];
len_cast4_i_cast_reg_1771[5] <= len_cast4_i_cast_fu_469_p1[5];
len_cast4_i_cast_reg_1771[6] <= len_cast4_i_cast_fu_469_p1[6];
len_cast4_i_cast_reg_1771[7] <= len_cast4_i_cast_fu_469_p1[7];
len_cast4_i_cast_reg_1771[8] <= len_cast4_i_cast_fu_469_p1[8];
len_cast4_i_cast_reg_1771[9] <= len_cast4_i_cast_fu_469_p1[9];
len_cast4_i_cast_reg_1771[10] <= len_cast4_i_cast_fu_469_p1[10];
        len_cast_i1_reg_1828[0] <= len_cast_i1_fu_527_p1[0];
len_cast_i1_reg_1828[1] <= len_cast_i1_fu_527_p1[1];
len_cast_i1_reg_1828[2] <= len_cast_i1_fu_527_p1[2];
len_cast_i1_reg_1828[3] <= len_cast_i1_fu_527_p1[3];
len_cast_i1_reg_1828[4] <= len_cast_i1_fu_527_p1[4];
len_cast_i1_reg_1828[5] <= len_cast_i1_fu_527_p1[5];
len_cast_i1_reg_1828[6] <= len_cast_i1_fu_527_p1[6];
len_cast_i1_reg_1828[7] <= len_cast_i1_fu_527_p1[7];
len_cast_i1_reg_1828[8] <= len_cast_i1_fu_527_p1[8];
len_cast_i1_reg_1828[9] <= len_cast_i1_fu_527_p1[9];
len_cast_i1_reg_1828[10] <= len_cast_i1_fu_527_p1[10];
        p_neg228_i_cast_reg_1755 <= p_neg228_i_cast_fu_453_p2;
        ref_cast_reg_1766[0] <= ref_cast_fu_465_p1[0];
ref_cast_reg_1766[1] <= ref_cast_fu_465_p1[1];
ref_cast_reg_1766[2] <= ref_cast_fu_465_p1[2];
ref_cast_reg_1766[3] <= ref_cast_fu_465_p1[3];
ref_cast_reg_1766[4] <= ref_cast_fu_465_p1[4];
ref_cast_reg_1766[5] <= ref_cast_fu_465_p1[5];
ref_cast_reg_1766[6] <= ref_cast_fu_465_p1[6];
ref_cast_reg_1766[7] <= ref_cast_fu_465_p1[7];
ref_cast_reg_1766[8] <= ref_cast_fu_465_p1[8];
ref_cast_reg_1766[9] <= ref_cast_fu_465_p1[9];
        ref_reg_1761 <= ref_fu_459_p2;
        tmp_17_reg_1812 <= tmp_17_fu_517_p1;
        tmp_1_i1_reg_1819 <= tmp_1_i1_fu_521_p2;
        tmp_27_cast_reg_1750[0] <= tmp_27_cast_fu_445_p1[0];
tmp_27_cast_reg_1750[1] <= tmp_27_cast_fu_445_p1[1];
tmp_27_cast_reg_1750[2] <= tmp_27_cast_fu_445_p1[2];
tmp_27_cast_reg_1750[3] <= tmp_27_cast_fu_445_p1[3];
tmp_27_cast_reg_1750[4] <= tmp_27_cast_fu_445_p1[4];
tmp_27_cast_reg_1750[5] <= tmp_27_cast_fu_445_p1[5];
tmp_27_cast_reg_1750[6] <= tmp_27_cast_fu_445_p1[6];
tmp_27_cast_reg_1750[7] <= tmp_27_cast_fu_445_p1[7];
tmp_27_cast_reg_1750[8] <= tmp_27_cast_fu_445_p1[8];
tmp_27_cast_reg_1750[9] <= tmp_27_cast_fu_445_p1[9];
tmp_27_cast_reg_1750[10] <= tmp_27_cast_fu_445_p1[10];
        tmp_5_cast_i_reg_1777[1] <= tmp_5_cast_i_fu_489_p1[1];
tmp_5_cast_i_reg_1777[2] <= tmp_5_cast_i_fu_489_p1[2];
tmp_5_cast_i_reg_1777[3] <= tmp_5_cast_i_fu_489_p1[3];
tmp_5_cast_i_reg_1777[4] <= tmp_5_cast_i_fu_489_p1[4];
tmp_5_cast_i_reg_1777[5] <= tmp_5_cast_i_fu_489_p1[5];
tmp_5_cast_i_reg_1777[6] <= tmp_5_cast_i_fu_489_p1[6];
tmp_5_cast_i_reg_1777[7] <= tmp_5_cast_i_fu_489_p1[7];
tmp_5_cast_i_reg_1777[8] <= tmp_5_cast_i_fu_489_p1[8];
tmp_5_cast_i_reg_1777[9] <= tmp_5_cast_i_fu_489_p1[9];
tmp_5_cast_i_reg_1777[10] <= tmp_5_cast_i_fu_489_p1[10];
tmp_5_cast_i_reg_1777[11] <= tmp_5_cast_i_fu_489_p1[11];
tmp_5_cast_i_reg_1777[12] <= tmp_5_cast_i_fu_489_p1[12];
tmp_5_cast_i_reg_1777[13] <= tmp_5_cast_i_fu_489_p1[13];
tmp_5_cast_i_reg_1777[14] <= tmp_5_cast_i_fu_489_p1[14];
        tmp_5_i1_reg_1834[1] <= tmp_5_i1_fu_541_p2[1];
tmp_5_i1_reg_1834[2] <= tmp_5_i1_fu_541_p2[2];
tmp_5_i1_reg_1834[3] <= tmp_5_i1_fu_541_p2[3];
tmp_5_i1_reg_1834[4] <= tmp_5_i1_fu_541_p2[4];
tmp_5_i1_reg_1834[5] <= tmp_5_i1_fu_541_p2[5];
tmp_5_i1_reg_1834[6] <= tmp_5_i1_fu_541_p2[6];
tmp_5_i1_reg_1834[7] <= tmp_5_i1_fu_541_p2[7];
tmp_5_i1_reg_1834[8] <= tmp_5_i1_fu_541_p2[8];
tmp_5_i1_reg_1834[9] <= tmp_5_i1_fu_541_p2[9];
tmp_5_i1_reg_1834[10] <= tmp_5_i1_fu_541_p2[10];
tmp_5_i1_reg_1834[11] <= tmp_5_i1_fu_541_p2[11];
tmp_5_i1_reg_1834[12] <= tmp_5_i1_fu_541_p2[12];
        tmp_5_i2_reg_1839 <= tmp_5_i2_fu_559_p2;
        widthloop_reg_1745 <= widthloop_fu_433_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        ap_reg_ppstg_col_assign_reg_2012_pp0_it1 <= col_assign_reg_2012;
        ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it1 <= or_cond221_i_reg_1972;
        ap_reg_ppstg_or_cond7_reg_2004_pp0_it1 <= or_cond7_reg_2004;
        ap_reg_ppstg_tmp_10_reg_2008_pp0_it1 <= tmp_10_reg_2008;
        ap_reg_ppstg_tmp_1_reg_1963_pp0_it1 <= tmp_1_reg_1963;
        ap_reg_ppstg_tmp_45_reg_1976_pp0_it1 <= tmp_45_reg_1976;
        ap_reg_ppstg_tmp_9_reg_2000_pp0_it1 <= tmp_9_reg_2000;
        tmp_1_reg_1963 <= tmp_1_fu_1004_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7)))) begin
        ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it2 <= ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it1;
        ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it3 <= ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it2;
        ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it4 <= ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it3;
        ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it5 <= ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it4;
        ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it6 <= ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it5;
        ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_2042_pp0_it3 <= src_kernel_win_0_val_0_1_6_reg_2042;
        ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_2059_pp0_it4 <= src_kernel_win_0_val_0_1_lo_reg_2059;
        ap_reg_ppstg_tmp_1_reg_1963_pp0_it2 <= ap_reg_ppstg_tmp_1_reg_1963_pp0_it1;
        ap_reg_ppstg_tmp_1_reg_1963_pp0_it3 <= ap_reg_ppstg_tmp_1_reg_1963_pp0_it2;
        src_kernel_win_0_val_0_1_6_reg_2042 <= src_kernel_win_0_val_0_1_fu_162;
        src_kernel_win_0_val_1_1_6_reg_2054 <= src_kernel_win_0_val_1_1_fu_178;
        src_kernel_win_0_val_2_1_9_reg_2048 <= src_kernel_win_0_val_2_1_fu_174;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(tmp_2_fu_569_p2 == ap_const_lv1_0))) begin
        brmerge_reg_1935 <= brmerge_fu_878_p2;
        newSel1_reg_1930 <= newSel1_fu_870_p3;
        sel_tmp1_i2_reg_1893 <= sel_tmp1_i2_fu_763_p2;
        sel_tmp1_i3_reg_1920 <= sel_tmp1_i3_fu_859_p2;
        sel_tmp6_demorgan_i2_reg_1898 <= sel_tmp6_demorgan_i2_fu_769_p2;
        sel_tmp6_demorgan_i3_reg_1925 <= sel_tmp6_demorgan_i3_fu_865_p2;
        sel_tmp_i2_reg_1888 <= sel_tmp_i2_fu_749_p3;
        tmp_25_reg_1858 <= ImagLoc_y_fu_586_p2[ap_const_lv32_A];
        tmp_26_reg_1867 <= tmp_26_fu_654_p1;
        tmp_30_reg_1873 <= tmp_30_fu_666_p3;
        tmp_36_reg_1878 <= tmp_36_fu_735_p1;
        tmp_37_reg_1903 <= tmp_37_fu_774_p1;
        tmp_3_i2_reg_1883 <= tmp_3_i2_fu_739_p2;
        tmp_3_i3_reg_1915 <= tmp_3_i3_fu_843_p2;
        tmp_3_reg_1853 <= tmp_3_fu_580_p2;
        tmp_41_reg_1910 <= tmp_41_fu_839_p1;
        tmp_i1_reg_1862 <= tmp_i1_fu_640_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_1_reg_1963) & (ap_const_lv1_0 == or_cond7_reg_2004) & (ap_const_lv1_0 == tmp_45_reg_1976) & (ap_const_lv1_0 == tmp_9_reg_2000))) begin
        col_assign_2_reg_2036 <= col_assign_2_fu_1187_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_1_fu_1004_p2) & ~(ap_const_lv1_0 == or_cond7_fu_1146_p2) & (ap_const_lv1_0 == tmp_10_fu_1152_p2))) begin
        col_assign_reg_2012 <= col_assign_fu_1157_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1) & ~(ap_reg_ppstg_col_assign_reg_2012_pp0_it1 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_reg_2012_pp0_it1 == ap_const_lv2_0))) begin
        col_buf_0_val_0_0_3_fu_170 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_2_fu_230 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1) & (ap_reg_ppstg_col_assign_reg_2012_pp0_it1 == ap_const_lv2_1))) begin
        col_buf_0_val_0_0_5_fu_186 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_1_fu_226 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1) & (ap_reg_ppstg_col_assign_reg_2012_pp0_it1 == ap_const_lv2_0))) begin
        col_buf_0_val_0_0_6_fu_194 <= k_buf_0_val_0_q0;
        right_border_buf_0_val_0_0_fu_222 <= k_buf_0_val_2_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        i_V_reg_1848 <= i_V_fu_574_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it4))) begin
        isneg_reg_2109 <= p_Val2_3_fu_1564_p2[ap_const_lv32_D];
        p_Val2_4_reg_2115 <= p_Val2_4_fu_1578_p1;
        tmp_15_reg_2120 <= {{p_Val2_3_fu_1564_p2[ap_const_lv32_D : ap_const_lv32_8]}};
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_1_reg_1963))) begin
        k_buf_0_val_0_addr_reg_2018 <= tmp_7_fu_1180_p1;
        k_buf_0_val_1_addr_reg_2024 <= tmp_7_fu_1180_p1;
        k_buf_0_val_2_addr_reg_2030 <= tmp_7_fu_1180_p1;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        locy_2_t_reg_1959 <= locy_2_t_fu_995_p2;
        sel_tmp1_reg_1944 <= sel_tmp1_fu_911_p2;
        sel_tmp3_reg_1949 <= sel_tmp3_fu_950_p2;
        sel_tmp5_reg_1954 <= sel_tmp5_fu_955_p2;
        sel_tmp8_reg_1939 <= sel_tmp8_fu_906_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_1_fu_1004_p2))) begin
        or_cond221_i_reg_1972 <= or_cond221_i_fu_1031_p2;
        p_p2_cast1_i_cast_reg_1980[0] <= p_p2_cast1_i_cast_fu_1101_p1[0];
p_p2_cast1_i_cast_reg_1980[1] <= p_p2_cast1_i_cast_fu_1101_p1[1];
p_p2_cast1_i_cast_reg_1980[2] <= p_p2_cast1_i_cast_fu_1101_p1[2];
p_p2_cast1_i_cast_reg_1980[3] <= p_p2_cast1_i_cast_fu_1101_p1[3];
p_p2_cast1_i_cast_reg_1980[4] <= p_p2_cast1_i_cast_fu_1101_p1[4];
p_p2_cast1_i_cast_reg_1980[5] <= p_p2_cast1_i_cast_fu_1101_p1[5];
p_p2_cast1_i_cast_reg_1980[6] <= p_p2_cast1_i_cast_fu_1101_p1[6];
p_p2_cast1_i_cast_reg_1980[7] <= p_p2_cast1_i_cast_fu_1101_p1[7];
p_p2_cast1_i_cast_reg_1980[8] <= p_p2_cast1_i_cast_fu_1101_p1[8];
p_p2_cast1_i_cast_reg_1980[9] <= p_p2_cast1_i_cast_fu_1101_p1[9];
p_p2_cast1_i_cast_reg_1980[10] <= p_p2_cast1_i_cast_fu_1101_p1[10];
p_p2_cast1_i_cast_reg_1980[11] <= p_p2_cast1_i_cast_fu_1101_p1[11];
p_p2_cast1_i_cast_reg_1980[12] <= p_p2_cast1_i_cast_fu_1101_p1[12];
p_p2_cast1_i_cast_reg_1980[13] <= p_p2_cast1_i_cast_fu_1101_p1[13];
        sel_tmp6_i_reg_1995 <= sel_tmp6_i_fu_1129_p2;
        sel_tmp_i_reg_1990 <= sel_tmp_i_fu_1115_p3;
        tmp_3_i_reg_1985 <= tmp_3_i_fu_1105_p2;
        tmp_45_reg_1976 <= ImagLoc_x_fu_1036_p2[ap_const_lv32_B];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_1_fu_1004_p2))) begin
        or_cond7_reg_2004 <= or_cond7_fu_1146_p2;
        tmp_9_reg_2000 <= tmp_9_fu_1141_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it2))) begin
        p_Val2_0_1_reg_2074 <= p_Val2_0_1_fu_1434_p2;
        p_Val2_0_2_reg_2079 <= p_Val2_0_2_fu_1443_p2;
        p_Val2_1_reg_2084 <= p_Val2_1_fu_1452_p2;
        p_Val2_s_reg_2069 <= p_Val2_s_fu_1425_p2;
        src_kernel_win_0_val_0_1_lo_reg_2059 <= src_kernel_win_0_val_0_1_fu_162;
        src_kernel_win_0_val_1_1_lo_reg_2064 <= src_kernel_win_0_val_1_1_fu_178;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it3))) begin
        p_Val2_1_2_reg_2094 <= p_Val2_1_2_fu_1505_p2;
        p_Val2_2_1_reg_2104 <= p_Val2_2_1_fu_1522_p2;
        p_Val2_2_reg_2099 <= p_Val2_2_fu_1514_p2;
        p_Val2_5_1_1_reg_2089 <= p_Val2_5_1_1_fu_1496_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it5))) begin
        p_Val2_6_reg_2125 <= p_Val2_6_fu_1621_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1) & ~(ap_reg_ppstg_col_assign_reg_2012_pp0_it1 == ap_const_lv2_1) & ~(ap_reg_ppstg_col_assign_reg_2012_pp0_it1 == ap_const_lv2_0)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1) & (ap_reg_ppstg_col_assign_reg_2012_pp0_it1 == ap_const_lv2_1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1) & (ap_reg_ppstg_col_assign_reg_2012_pp0_it1 == ap_const_lv2_0)))) begin
        right_border_buf_0_val_1_2_1_fu_198 <= right_border_buf_0_val_1_2_8_fu_1382_p3;
        right_border_buf_0_val_1_2_2_fu_202 <= right_border_buf_0_val_1_2_6_fu_1373_p3;
        right_border_buf_0_val_1_2_7_fu_206 <= right_border_buf_0_val_1_2_4_fu_1356_p3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it4) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it3))) begin
        src_kernel_win_0_val_0_2_fu_166 <= ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_2042_pp0_it3;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it3) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it2))) begin
        src_kernel_win_0_val_1_2_fu_182 <= src_kernel_win_0_val_1_1_6_reg_2054;
        src_kernel_win_0_val_2_2_fu_190 <= src_kernel_win_0_val_2_1_9_reg_2048;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == tmp_1_fu_1004_p2) & ~(ap_const_lv1_0 == or_cond7_fu_1146_p2))) begin
        tmp_10_reg_2008 <= tmp_10_fu_1152_p2;
    end
end

/// ap_done assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0 or ap_sig_cseq_ST_st2_fsm_1 or tmp_2_fu_569_p2)
begin
    if (((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_2_fu_569_p2 == ap_const_lv1_0)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (ap_sig_cseq_ST_st2_fsm_1 or tmp_2_fu_569_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (tmp_2_fu_569_p2 == ap_const_lv1_0))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_pp0_stg0_fsm_3 assign process. ///
always @ (ap_sig_bdd_161)
begin
    if (ap_sig_bdd_161) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_4 assign process. ///
always @ (ap_sig_bdd_375)
begin
    if (ap_sig_bdd_375) begin
        ap_sig_cseq_ST_st12_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_23)
begin
    if (ap_sig_bdd_23) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_96)
begin
    if (ap_sig_bdd_96) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_144)
begin
    if (ap_sig_bdd_144) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        k_buf_0_val_0_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_ce1 assign process. ///
always @ (ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        k_buf_0_val_0_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_0_we1 assign process. ///
always @ (brmerge_reg_1935 or ap_reg_ppstg_tmp_1_reg_1963_pp0_it1 or ap_reg_ppstg_or_cond7_reg_2004_pp0_it1 or ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        k_buf_0_val_0_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_0_we1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        k_buf_0_val_1_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_ce1 assign process. ///
always @ (brmerge_reg_1935 or ap_reg_ppstg_tmp_1_reg_1963_pp0_it1 or ap_reg_ppstg_or_cond7_reg_2004_pp0_it1 or ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)))) begin
        k_buf_0_val_1_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_1_we1 assign process. ///
always @ (brmerge_reg_1935 or ap_reg_ppstg_tmp_1_reg_1963_pp0_it1 or ap_reg_ppstg_or_cond7_reg_2004_pp0_it1 or ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)))) begin
        k_buf_0_val_1_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_1_we1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_ce0 assign process. ///
always @ (ap_sig_cseq_ST_pp0_stg0_fsm_3 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_3) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        k_buf_0_val_2_ce0 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_ce0 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_ce1 assign process. ///
always @ (brmerge_reg_1935 or ap_reg_ppstg_tmp_1_reg_1963_pp0_it1 or ap_reg_ppstg_or_cond7_reg_2004_pp0_it1 or ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)))) begin
        k_buf_0_val_2_ce1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_ce1 = ap_const_logic_0;
    end
end

/// k_buf_0_val_2_we1 assign process. ///
always @ (brmerge_reg_1935 or ap_reg_ppstg_tmp_1_reg_1963_pp0_it1 or ap_reg_ppstg_or_cond7_reg_2004_pp0_it1 or ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7 or ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)
begin
    if (((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & (ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)) | (~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_10_reg_2008_pp0_it1)))) begin
        k_buf_0_val_2_we1 = ap_const_logic_1;
    end else begin
        k_buf_0_val_2_we1 = ap_const_logic_0;
    end
end

/// p_dst_data_stream_V_write assign process. ///
always @ (ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it6 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it6) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_dst_data_stream_V_write = ap_const_logic_1;
    end else begin
        p_dst_data_stream_V_write = ap_const_logic_0;
    end
end

/// p_src_data_stream_V_read assign process. ///
always @ (brmerge_reg_1935 or ap_reg_ppstg_tmp_1_reg_1963_pp0_it1 or ap_reg_ppstg_or_cond7_reg_2004_pp0_it1 or ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7)
begin
    if ((~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))))) begin
        p_src_data_stream_V_read = ap_const_logic_1;
    end else begin
        p_src_data_stream_V_read = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or tmp_2_fu_569_p2 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_180 or ap_reg_ppiten_pp0_it2 or ap_reg_ppiten_pp0_it3 or ap_reg_ppiten_pp0_it6 or ap_sig_bdd_198 or ap_reg_ppiten_pp0_it7)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~(ap_start == ap_const_logic_0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((tmp_2_fu_569_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
        end
        ap_ST_pp0_stg0_fsm_3 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it7) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it6)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_180 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it2)) | (ap_sig_bdd_198 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it7))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it3)))) begin
                ap_NS_fsm = ap_ST_st12_fsm_4;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_3;
            end
        end
        ap_ST_st12_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_1036_p2 = ($signed(tmp_31_cast6_fu_1000_p1) + $signed(ap_const_lv12_FFF));
assign ImagLoc_y_fu_586_p2 = ($signed(tmp_28_cast7_fu_565_p1) + $signed(ap_const_lv11_7FC));
assign OP1_V_0_cast_fu_1421_p1 = src_kernel_win_0_val_2_2_fu_190;
assign OP2_V_0_1_cast_fu_493_p1 = $signed(p_kernel_val_0_V_1_read);
assign OP2_V_0_2_cast_fu_497_p1 = $signed(p_kernel_val_0_V_2_read);
assign OP2_V_1_2_cast_fu_505_p1 = $signed(p_kernel_val_1_V_2_read);
assign OP2_V_1_cast_fu_501_p1 = $signed(p_kernel_val_1_V_0_read);
assign OP2_V_2_1_cast_fu_513_p1 = $signed(p_kernel_val_2_V_1_read);
assign OP2_V_2_cast_fu_509_p1 = $signed(p_kernel_val_2_V_0_read);

/// ap_sig_bdd_144 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_144 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_161 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_161 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end

/// ap_sig_bdd_180 assign process. ///
always @ (p_src_data_stream_V_empty_n or brmerge_reg_1935 or ap_reg_ppstg_tmp_1_reg_1963_pp0_it1 or ap_reg_ppstg_or_cond7_reg_2004_pp0_it1)
begin
    ap_sig_bdd_180 = ((p_src_data_stream_V_empty_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_tmp_1_reg_1963_pp0_it1) & ~(ap_const_lv1_0 == brmerge_reg_1935) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond7_reg_2004_pp0_it1));
end

/// ap_sig_bdd_198 assign process. ///
always @ (p_dst_data_stream_V_full_n or ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it6)
begin
    ap_sig_bdd_198 = ((p_dst_data_stream_V_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == ap_reg_ppstg_or_cond221_i_reg_1972_pp0_it6));
end

/// ap_sig_bdd_23 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_23 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_375 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_375 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_96 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_96 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end
assign brmerge_fu_878_p2 = (tmp_4_fu_592_p2 | or_cond6_fu_619_p2);
assign col_assign_2_fu_1187_p2 = (tmp_46_fu_1176_p1 + p_neg228_i_cast_reg_1755);
assign col_assign_fu_1157_p2 = (tmp_43_fu_1042_p1 + p_neg228_i_cast_reg_1755);
assign col_buf_0_val_0_0_2_fu_1260_p3 = ((sel_tmp_fu_1255_p2)? col_buf_0_val_0_0_5_fu_186: col_buf_0_val_0_0_3_fu_170);
assign col_buf_0_val_0_0_9_fu_1273_p3 = ((sel_tmp2_fu_1268_p2)? col_buf_0_val_0_0_6_fu_194: col_buf_0_val_0_0_2_fu_1260_p3);
assign heightloop_fu_427_p2 = (tmp_11_fu_419_p1 + ap_const_lv10_5);
assign i_V_fu_574_p2 = (p_012_0_i_reg_344 + ap_const_lv10_1);
assign icmp1_fu_1025_p2 = (tmp_42_fu_1015_p4 != ap_const_lv10_0? 1'b1: 1'b0);
assign icmp_fu_608_p2 = ($signed(tmp_24_fu_598_p4) > $signed(10'b0000000000)? 1'b1: 1'b0);
assign j_V_fu_1009_p2 = (p_025_0_i_reg_355 + ap_const_lv11_1);
assign k_buf_0_val_0_address0 = tmp_7_fu_1180_p1;
assign k_buf_0_val_0_address1 = k_buf_0_val_0_addr_reg_2018;
assign k_buf_0_val_0_d1 = p_src_data_stream_V_dout;
assign k_buf_0_val_1_address0 = tmp_7_fu_1180_p1;
assign k_buf_0_val_1_address1 = k_buf_0_val_1_addr_reg_2024;
assign k_buf_0_val_1_d1 = k_buf_0_val_0_q0;
assign k_buf_0_val_2_address0 = tmp_7_fu_1180_p1;
assign k_buf_0_val_2_address1 = k_buf_0_val_2_addr_reg_2030;
assign k_buf_0_val_2_d1 = k_buf_0_val_1_q0;
assign len_cast4_i_cast_fu_469_p1 = tmp_12_fu_423_p1;
assign len_cast_i1_fu_527_p1 = tmp_17_fu_517_p1;
assign locy_1_t_fu_945_p2 = (tmp_37_reg_1903 - p_assign_2_i2_fu_938_p3);
assign locy_2_t_fu_995_p2 = (tmp_37_reg_1903 - newSel2_fu_988_p3);
assign newSel1_fu_870_p3 = ((or_cond_i3_fu_807_p2)? tmp_39_fu_813_p1: p_assign_1_cast_i1_fu_848_p2);
assign newSel2_fu_988_p3 = ((or_cond_fu_982_p2)? newSel_fu_975_p3: newSel1_reg_1930);
assign newSel_fu_975_p3 = ((sel_tmp7_i3_fu_970_p2)? tmp_41_reg_1910: ap_const_lv2_0);
assign not_i_i_i_fu_1597_p2 = (tmp_15_reg_2120 != ap_const_lv6_0? 1'b1: 1'b0);
assign or_cond221_i_fu_1031_p2 = (tmp_3_reg_1853 & icmp1_fu_1025_p2);
assign or_cond6_fu_619_p2 = (icmp_fu_608_p2 & tmp_6_fu_614_p2);
assign or_cond7_fu_1146_p2 = (tmp_8_fu_1135_p2 & tmp_9_fu_1141_p2);
assign or_cond_fu_982_p2 = (sel_tmp7_i3_fu_970_p2 | sel_tmp2_i3_fu_961_p2);
assign or_cond_i1_fu_1065_p2 = (tmp_i_fu_1060_p2 & rev2_fu_1054_p2);
assign or_cond_i2_fu_703_p2 = (tmp_i2_fu_698_p2 & rev_fu_688_p2);
assign or_cond_i3_fu_807_p2 = (tmp_i3_fu_802_p2 & rev1_fu_792_p2);
assign overflow_fu_1602_p2 = (not_i_i_i_fu_1597_p2 & tmp_i_i_fu_1592_p2);
assign p_Val2_0_1_fu_1434_p0 = p_Val2_0_1_fu_1434_p00;
assign p_Val2_0_1_fu_1434_p00 = src_kernel_win_0_val_2_1_9_reg_2048;
assign p_Val2_0_1_fu_1434_p1 = OP2_V_0_1_cast_reg_1782;
assign p_Val2_0_1_fu_1434_p2 = ($signed({{1'b0}, {p_Val2_0_1_fu_1434_p0}}) * $signed(p_Val2_0_1_fu_1434_p1));
assign p_Val2_0_2_fu_1443_p0 = p_Val2_0_2_fu_1443_p00;
assign p_Val2_0_2_fu_1443_p00 = src_kernel_win_0_val_2_1_fu_174;
assign p_Val2_0_2_fu_1443_p1 = OP2_V_0_2_cast_reg_1787;
assign p_Val2_0_2_fu_1443_p2 = ($signed({{1'b0}, {p_Val2_0_2_fu_1443_p0}}) * $signed(p_Val2_0_2_fu_1443_p1));
assign p_Val2_1_2_fu_1505_p0 = p_Val2_1_2_fu_1505_p00;
assign p_Val2_1_2_fu_1505_p00 = src_kernel_win_0_val_1_1_lo_reg_2064;
assign p_Val2_1_2_fu_1505_p1 = OP2_V_1_2_cast_reg_1797;
assign p_Val2_1_2_fu_1505_p2 = ($signed({{1'b0}, {p_Val2_1_2_fu_1505_p0}}) * $signed(p_Val2_1_2_fu_1505_p1));
assign p_Val2_1_fu_1452_p0 = p_Val2_1_fu_1452_p00;
assign p_Val2_1_fu_1452_p00 = src_kernel_win_0_val_1_2_fu_182;
assign p_Val2_1_fu_1452_p1 = OP2_V_1_cast_reg_1792;
assign p_Val2_1_fu_1452_p2 = ($signed({{1'b0}, {p_Val2_1_fu_1452_p0}}) * $signed(p_Val2_1_fu_1452_p1));
assign p_Val2_2_1_fu_1522_p0 = p_Val2_2_1_fu_1522_p00;
assign p_Val2_2_1_fu_1522_p00 = ap_reg_ppstg_src_kernel_win_0_val_0_1_6_reg_2042_pp0_it3;
assign p_Val2_2_1_fu_1522_p1 = OP2_V_2_1_cast_reg_1807;
assign p_Val2_2_1_fu_1522_p2 = ($signed({{1'b0}, {p_Val2_2_1_fu_1522_p0}}) * $signed(p_Val2_2_1_fu_1522_p1));
assign p_Val2_2_cast_cast_fu_1539_p1 = p_Val2_2_reg_2099;
assign p_Val2_2_fu_1514_p0 = p_Val2_2_fu_1514_p00;
assign p_Val2_2_fu_1514_p00 = src_kernel_win_0_val_0_2_fu_166;
assign p_Val2_2_fu_1514_p1 = OP2_V_2_cast_reg_1802;
assign p_Val2_2_fu_1514_p2 = ($signed({{1'b0}, {p_Val2_2_fu_1514_p0}}) * $signed(p_Val2_2_fu_1514_p1));
assign p_Val2_3_fu_1564_p2 = ($signed(p_Val2_5_2_1_fu_1555_p2) + $signed(tmp_160_2_2_cast_cast_fu_1561_p1));
assign p_Val2_4_fu_1578_p1 = p_Val2_3_fu_1564_p2[7:0];
assign p_Val2_5_0_1_fu_1474_p2 = ($signed(tmp_160_0_1_cast_fu_1471_p1) + $signed(tmp_160_0_cast_fu_1468_p1));
assign p_Val2_5_0_2_cast_fu_1489_p1 = p_Val2_5_0_2_fu_1483_p2;
assign p_Val2_5_0_2_fu_1483_p2 = ($signed(p_Val2_5_0_1_fu_1474_p2) + $signed(tmp_160_0_2_cast_cast_fu_1480_p1));
assign p_Val2_5_1_1_fu_1496_p2 = ($signed(p_Val2_5_0_2_cast_fu_1489_p1) + $signed(tmp_160_1_cast_cast_fu_1493_p1));
assign p_Val2_5_1_2_fu_1534_p2 = ($signed(p_Val2_5_1_1_reg_2089) + $signed(tmp_160_1_2_cast_cast_fu_1531_p1));
assign p_Val2_5_2_1_fu_1555_p2 = ($signed(p_Val2_5_2_cast_cast_fu_1548_p1) + $signed(tmp_160_2_1_cast_cast_fu_1552_p1));
assign p_Val2_5_2_cast_cast_fu_1548_p1 = p_Val2_5_2_fu_1542_p2;
assign p_Val2_5_2_fu_1542_p2 = ($signed(p_Val2_5_1_2_fu_1534_p2) + $signed(p_Val2_2_cast_cast_fu_1539_p1));
assign p_Val2_6_fu_1621_p3 = ((tmp_i_i_42_fu_1616_p2)? p_mux_i_i_cast_fu_1608_p3: p_Val2_4_reg_2115);
assign p_Val2_s_fu_1425_p2 = (ap_const_lv9_0 - OP1_V_0_cast_fu_1421_p1);
assign p_assign_1_cast_i1_fu_848_p2 = (tmp_5_i2_reg_1839 - tmp_41_fu_839_p1);
assign p_assign_1_cast_i_fu_744_p2 = (tmp_5_i2_reg_1839 - tmp_36_fu_735_p1);
assign p_assign_1_fu_1110_p2 = ($signed(tmp_5_cast_i_reg_1777) - $signed(p_p2_cast1_i_cast_fu_1101_p1));
assign p_assign_2_fu_649_p2 = (tmp_5_i1_reg_1834 - p_cast_i32_cast_fu_645_p1);
assign p_assign_2_i2_fu_938_p3 = ((sel_tmp7_i2_fu_933_p2)? tmp_36_reg_1878: sel_tmp3_i2_fu_921_p3);
assign p_assign_2_i_fu_1166_p3 = ((sel_tmp7_i_fu_1162_p2)? p_p2_cast1_i_cast_reg_1980: sel_tmp_i_reg_1990);
assign p_assign_3_fu_721_p2 = (ap_const_lv11_5 - tmp_28_cast7_fu_565_p1);
assign p_assign_4_fu_825_p2 = (ap_const_lv11_6 - tmp_28_cast7_fu_565_p1);
assign p_assign_fu_1083_p2 = (ap_const_lv12_1 - tmp_31_cast6_fu_1000_p1);
assign p_cast8_i57_cast_fu_694_p1 = $signed(y_1_fu_674_p2);
assign p_cast8_i88_cast_fu_798_p1 = $signed(y_1_1_fu_778_p2);
assign p_cast_i32_cast_fu_645_p1 = ImagLoc_y_fu_586_p2;
assign p_cast_i_cast_fu_1071_p1 = $signed(ImagLoc_x_fu_1036_p2);
assign p_dst_data_stream_V_din = p_Val2_6_reg_2125;
assign p_i_fu_633_p3 = ((tmp_6_fu_614_p2)? ap_const_lv10_2: ref_reg_1761);
assign p_mux_i_i_cast_fu_1608_p3 = ((tmp_i_i_fu_1592_p2)? ap_const_lv8_FF: ap_const_lv8_0);
assign p_neg228_i_cast_fu_453_p2 = (tmp_13_fu_449_p1 ^ ap_const_lv2_3);
assign p_p2_cast1_i_cast_fu_1101_p1 = $unsigned(p_p2_i_cast_fu_1097_p1);
assign p_p2_i1_fu_727_p3 = ((tmp_35_fu_713_p3)? p_assign_3_fu_721_p2: y_1_fu_674_p2);
assign p_p2_i2_fu_831_p3 = ((tmp_40_fu_817_p3)? p_assign_4_fu_825_p2: y_1_1_fu_778_p2);
assign p_p2_i_cast_fu_1097_p1 = $signed(p_p2_i_fu_1089_p3);
assign p_p2_i_fu_1089_p3 = ((tmp_45_fu_1075_p3)? p_assign_fu_1083_p2: ImagLoc_x_fu_1036_p2);
assign ref_cast_fu_465_p1 = ref_fu_459_p2;
assign ref_fu_459_p2 = ($signed(tmp_11_fu_419_p1) + $signed(ap_const_lv10_3FF));
assign rev1_fu_792_p2 = (tmp_38_fu_784_p3 ^ ap_const_lv1_1);
assign rev2_fu_1054_p2 = (tmp_44_fu_1046_p3 ^ ap_const_lv1_1);
assign rev_fu_688_p2 = (tmp_33_fu_680_p3 ^ ap_const_lv1_1);
assign right_border_buf_0_val_1_2_11_fu_1290_p3 = ((sel_tmp2_fu_1268_p2)? right_border_buf_0_val_1_2_1_fu_198: right_border_buf_0_val_1_2_fu_1282_p3);
assign right_border_buf_0_val_1_2_3_fu_1343_p3 = ((sel_tmp6_fu_1338_p2)? right_border_buf_0_val_1_2_7_fu_206: k_buf_0_val_1_q0);
assign right_border_buf_0_val_1_2_4_fu_1356_p3 = ((sel_tmp7_fu_1351_p2)? right_border_buf_0_val_1_2_7_fu_206: right_border_buf_0_val_1_2_3_fu_1343_p3);
assign right_border_buf_0_val_1_2_5_fu_1365_p3 = ((sel_tmp6_fu_1338_p2)? k_buf_0_val_1_q0: right_border_buf_0_val_1_2_2_fu_202);
assign right_border_buf_0_val_1_2_6_fu_1373_p3 = ((sel_tmp7_fu_1351_p2)? right_border_buf_0_val_1_2_2_fu_202: right_border_buf_0_val_1_2_5_fu_1365_p3);
assign right_border_buf_0_val_1_2_8_fu_1382_p3 = ((sel_tmp7_fu_1351_p2)? k_buf_0_val_1_q0: right_border_buf_0_val_1_2_1_fu_198);
assign right_border_buf_0_val_1_2_fu_1282_p3 = ((sel_tmp_fu_1255_p2)? right_border_buf_0_val_1_2_2_fu_202: right_border_buf_0_val_1_2_7_fu_206);
assign sel_tmp1_fu_911_p2 = (tmp_32_fu_901_p2 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp1_i1_fu_884_p2 = (tmp_i1_reg_1862 ^ ap_const_lv1_1);
assign sel_tmp1_i2_fu_763_p2 = (tmp_33_fu_680_p3 | tmp_i2_not_fu_757_p2);
assign sel_tmp1_i3_fu_859_p2 = (tmp_38_fu_784_p3 | tmp_i3_not_fu_853_p2);
assign sel_tmp2_fu_1268_p2 = (col_assign_2_reg_2036 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp2_i1_fu_889_p2 = (tmp_1_i1_reg_1819 & sel_tmp1_i1_fu_884_p2);
assign sel_tmp2_i2_fu_917_p2 = (tmp_1_i1_reg_1819 & sel_tmp1_i2_reg_1893);
assign sel_tmp2_i3_fu_961_p2 = (tmp_1_i1_reg_1819 & sel_tmp1_i3_reg_1920);
assign sel_tmp3_fu_950_p2 = (tmp_37_reg_1903 == p_assign_2_i2_fu_938_p3? 1'b1: 1'b0);
assign sel_tmp3_i2_fu_921_p3 = ((sel_tmp2_i2_fu_917_p2)? ap_const_lv2_0: sel_tmp_i2_reg_1888);
assign sel_tmp4_fu_1221_p3 = ((sel_tmp3_reg_1949)? k_buf_0_val_0_q0: k_buf_0_val_2_q0);
assign sel_tmp5_fu_955_p2 = (locy_1_t_fu_945_p2 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp6_demorgan_i2_fu_769_p2 = (or_cond_i2_fu_703_p2 | tmp_1_i1_reg_1819);
assign sel_tmp6_demorgan_i3_fu_865_p2 = (or_cond_i3_fu_807_p2 | tmp_1_i1_reg_1819);
assign sel_tmp6_fu_1338_p2 = (ap_reg_ppstg_col_assign_reg_2012_pp0_it1 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp6_i2_fu_928_p2 = (sel_tmp6_demorgan_i2_reg_1898 ^ ap_const_lv1_1);
assign sel_tmp6_i3_fu_965_p2 = (sel_tmp6_demorgan_i3_reg_1925 ^ ap_const_lv1_1);
assign sel_tmp6_i_fu_1129_p2 = (tmp_44_fu_1046_p3 | tmp_i_not_fu_1123_p2);
assign sel_tmp7_fu_1351_p2 = (ap_reg_ppstg_col_assign_reg_2012_pp0_it1 == ap_const_lv2_0? 1'b1: 1'b0);
assign sel_tmp7_i2_fu_933_p2 = (tmp_3_i2_reg_1883 & sel_tmp6_i2_fu_928_p2);
assign sel_tmp7_i3_fu_970_p2 = (tmp_3_i3_reg_1915 & sel_tmp6_i3_fu_965_p2);
assign sel_tmp7_i_fu_1162_p2 = (tmp_3_i_reg_1985 & sel_tmp6_i_reg_1995);
assign sel_tmp8_fu_906_p2 = (tmp_26_reg_1867 == tmp_31_fu_894_p3? 1'b1: 1'b0);
assign sel_tmp9_fu_1206_p3 = ((sel_tmp8_reg_1939)? k_buf_0_val_0_q0: k_buf_0_val_2_q0);
assign sel_tmp_fu_1255_p2 = (col_assign_2_reg_2036 == ap_const_lv2_1? 1'b1: 1'b0);
assign sel_tmp_i2_fu_749_p3 = ((or_cond_i2_fu_703_p2)? tmp_34_fu_709_p1: p_assign_1_cast_i_fu_744_p2);
assign sel_tmp_i_fu_1115_p3 = ((or_cond_i1_fu_1065_p2)? p_cast_i_cast_fu_1071_p1: p_assign_1_fu_1110_p2);
assign src_kernel_win_0_val_0_0_fu_1213_p3 = ((sel_tmp1_reg_1944)? k_buf_0_val_1_q0: sel_tmp9_fu_1206_p3);
assign src_kernel_win_0_val_1_0_fu_1228_p3 = ((sel_tmp5_reg_1954)? k_buf_0_val_1_q0: sel_tmp4_fu_1221_p3);
assign tmp_10_fu_1152_p2 = ($signed(ImagLoc_x_fu_1036_p2) < $signed(tmp_27_cast_reg_1750)? 1'b1: 1'b0);
assign tmp_11_fu_419_p1 = p_src_rows_V_read[9:0];
assign tmp_12_fu_423_p1 = p_src_cols_V_read[10:0];
assign tmp_13_fu_449_p1 = p_src_cols_V_read[1:0];
assign tmp_14_fu_473_p2 = p_src_cols_V_read << ap_const_lv12_1;
assign tmp_160_0_1_cast_fu_1471_p1 = p_Val2_0_1_reg_2074;
assign tmp_160_0_2_cast_cast_fu_1480_p1 = p_Val2_0_2_reg_2079;
assign tmp_160_0_cast_fu_1468_p1 = $signed(p_Val2_s_reg_2069);
assign tmp_160_1_2_cast_cast_fu_1531_p1 = p_Val2_1_2_reg_2094;
assign tmp_160_1_cast_cast_fu_1493_p1 = p_Val2_1_reg_2084;
assign tmp_160_2_1_cast_cast_fu_1552_p1 = p_Val2_2_1_reg_2104;
assign tmp_160_2_2_cast_cast_fu_1561_p1 = ap_reg_ppstg_src_kernel_win_0_val_0_1_lo_reg_2059_pp0_it4;
assign tmp_17_fu_517_p1 = p_src_rows_V_read[10:0];
assign tmp_18_fu_531_p2 = p_src_rows_V_read << ap_const_lv12_1;
assign tmp_19_fu_547_p1 = p_src_rows_V_read[0:0];
assign tmp_1_fu_1004_p2 = (p_025_0_i_reg_355 < widthloop_reg_1745? 1'b1: 1'b0);
assign tmp_1_i1_fu_521_p2 = (tmp_17_fu_517_p1 == ap_const_lv11_1? 1'b1: 1'b0);
assign tmp_24_fu_598_p4 = {{ImagLoc_y_fu_586_p2[ap_const_lv32_A : ap_const_lv32_1]}};
assign tmp_26_fu_654_p1 = p_i_fu_633_p3[1:0];
assign tmp_27_cast_fu_445_p1 = tmp_s_fu_439_p2;
assign tmp_28_cast7_fu_565_p1 = p_012_0_i_reg_344;
assign tmp_28_fu_658_p1 = ImagLoc_y_fu_586_p2[1:0];
assign tmp_29_fu_662_p1 = p_assign_2_fu_649_p2[1:0];
assign tmp_2_fu_569_p2 = (p_012_0_i_reg_344 < heightloop_reg_1740? 1'b1: 1'b0);
assign tmp_30_fu_666_p3 = ((tmp_i1_fu_640_p2)? tmp_28_fu_658_p1: tmp_29_fu_662_p1);
assign tmp_31_cast6_fu_1000_p1 = p_025_0_i_reg_355;
assign tmp_31_fu_894_p3 = ((sel_tmp2_i1_fu_889_p2)? ap_const_lv2_0: tmp_30_reg_1873);
assign tmp_32_fu_901_p2 = (tmp_26_reg_1867 - tmp_31_fu_894_p3);
assign tmp_33_fu_680_p3 = y_1_fu_674_p2[ap_const_lv32_A];
assign tmp_34_fu_709_p1 = y_1_fu_674_p2[1:0];
assign tmp_35_fu_713_p3 = y_1_fu_674_p2[ap_const_lv32_A];
assign tmp_36_fu_735_p1 = p_p2_i1_fu_727_p3[1:0];
assign tmp_37_fu_774_p1 = p_i_fu_633_p3[1:0];
assign tmp_38_fu_784_p3 = y_1_1_fu_778_p2[ap_const_lv32_A];
assign tmp_39_fu_813_p1 = y_1_1_fu_778_p2[1:0];
assign tmp_3_fu_580_p2 = (p_012_0_i_reg_344 > ap_const_lv10_4? 1'b1: 1'b0);
assign tmp_3_i2_fu_739_p2 = (p_p2_i1_fu_727_p3 < tmp_17_reg_1812? 1'b1: 1'b0);
assign tmp_3_i3_fu_843_p2 = (p_p2_i2_fu_831_p3 < tmp_17_reg_1812? 1'b1: 1'b0);
assign tmp_3_i_fu_1105_p2 = (p_p2_i_fu_1089_p3 < len_cast4_i_cast_reg_1771? 1'b1: 1'b0);
assign tmp_40_fu_817_p3 = y_1_1_fu_778_p2[ap_const_lv32_A];
assign tmp_41_fu_839_p1 = p_p2_i2_fu_831_p3[1:0];
assign tmp_42_fu_1015_p4 = {{p_025_0_i_reg_355[ap_const_lv32_A : ap_const_lv32_1]}};
assign tmp_43_fu_1042_p1 = ImagLoc_x_fu_1036_p2[1:0];
assign tmp_44_fu_1046_p3 = ImagLoc_x_fu_1036_p2[ap_const_lv32_B];
assign tmp_45_fu_1075_p3 = ImagLoc_x_fu_1036_p2[ap_const_lv32_B];
assign tmp_46_fu_1176_p1 = p_assign_2_i_fu_1166_p3[1:0];
assign tmp_4_cast_i42_cast_fu_537_p1 = tmp_18_fu_531_p2;
assign tmp_4_cast_i_cast_fu_479_p1 = tmp_14_fu_473_p2;
assign tmp_4_fu_592_p2 = ($signed(ImagLoc_y_fu_586_p2) < $signed(11'b11111111111)? 1'b1: 1'b0);
assign tmp_4_i2_fu_551_p3 = {{tmp_19_fu_547_p1}, {ap_const_lv1_0}};
assign tmp_5_cast_i_fu_489_p1 = $signed(tmp_5_i_fu_483_p2);
assign tmp_5_i1_fu_541_p2 = (tmp_4_cast_i42_cast_fu_537_p1 + ap_const_lv13_2);
assign tmp_5_i2_fu_559_p2 = (tmp_4_i2_fu_551_p3 ^ ap_const_lv2_2);
assign tmp_5_i_fu_483_p2 = ($signed(tmp_4_cast_i_cast_fu_479_p1) + $signed(ap_const_lv13_1FFE));
assign tmp_6_fu_614_p2 = ($signed(ImagLoc_y_fu_586_p2) < $signed(ref_cast_reg_1766)? 1'b1: 1'b0);
assign tmp_7_fu_1180_p1 = $unsigned(x_fu_1172_p1);
assign tmp_8_fu_1135_p2 = (p_025_0_i_reg_355 != ap_const_lv11_0? 1'b1: 1'b0);
assign tmp_9_fu_1141_p2 = ($signed(ImagLoc_x_fu_1036_p2) < $signed(p_src_cols_V_read)? 1'b1: 1'b0);
assign tmp_i1_fu_640_p2 = (ImagLoc_y_fu_586_p2 < tmp_17_reg_1812? 1'b1: 1'b0);
assign tmp_i2_fu_698_p2 = ($signed(p_cast8_i57_cast_fu_694_p1) < $signed(len_cast_i1_reg_1828)? 1'b1: 1'b0);
assign tmp_i2_not_fu_757_p2 = (tmp_i2_fu_698_p2 ^ ap_const_lv1_1);
assign tmp_i3_fu_802_p2 = ($signed(p_cast8_i88_cast_fu_798_p1) < $signed(len_cast_i1_reg_1828)? 1'b1: 1'b0);
assign tmp_i3_not_fu_853_p2 = (tmp_i3_fu_802_p2 ^ ap_const_lv1_1);
assign tmp_i_fu_1060_p2 = ($signed(ImagLoc_x_fu_1036_p2) < $signed(len_cast4_i_cast_reg_1771)? 1'b1: 1'b0);
assign tmp_i_i_42_fu_1616_p2 = (isneg_reg_2109 | overflow_fu_1602_p2);
assign tmp_i_i_fu_1592_p2 = (isneg_reg_2109 ^ ap_const_lv1_1);
assign tmp_i_not_fu_1123_p2 = (tmp_i_fu_1060_p2 ^ ap_const_lv1_1);
assign tmp_s_fu_439_p2 = ($signed(tmp_12_fu_423_p1) + $signed(ap_const_lv11_7FD));
assign widthloop_fu_433_p2 = (tmp_12_fu_423_p1 + ap_const_lv11_2);
assign x_fu_1172_p1 = $signed(p_assign_2_i_fu_1166_p3);
assign y_1_1_fu_778_p2 = ($signed(tmp_28_cast7_fu_565_p1) + $signed(ap_const_lv11_7FA));
assign y_1_fu_674_p2 = ($signed(tmp_28_cast7_fu_565_p1) + $signed(ap_const_lv11_7FB));
always @ (posedge ap_clk)
begin
    tmp_27_cast_reg_1750[11] <= 1'b0;
    ref_cast_reg_1766[10] <= 1'b0;
    len_cast4_i_cast_reg_1771[11] <= 1'b0;
    tmp_5_cast_i_reg_1777[0] <= 1'b0;
    len_cast_i1_reg_1828[11] <= 1'b0;
    tmp_5_i1_reg_1834[0] <= 1'b0;
    p_p2_cast1_i_cast_reg_1980[14] <= 1'b0;
end



endmodule //sobel_Filter2D

